### ISSUE TITLE
投稿コンテンツが表示されなくなる？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1001]
特定環境下で投稿ページなどの本文が表示されなくなる。
過去にも同様の報告が数件あったが原因はわからなかった。

以下の行をコメントアウトすると表示されるようになる

https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/e3ec5fe31a1450d2c0730238fee0d89739480e55/inc/template-tags/package/template-tags.php#L291-L292

**Comment by kurudrive** [comment]
@drill-lancer 
ディスクリプションってブロックと関係ないように思うんだけどこの do_blocks() は何をしてるの？

**Comment by drill-lancer** [comment]
@kurudrive 
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/e3ec5fe31a1450d2c0730238fee0d89739480e55/inc/template-tags/package/template-tags.php#L259-L265
上記で post_content が選ばれた場合 post_content にはブロックが処理される前の状態で保存されているのでそれを展開しています。

**Comment by kurudrive** [comment]
@drill-lancer 原因調査よろしくお願いいたします。

データは discord で渡します。

今わかっている事

* 僕のローカルでは再現しない。もらったデータでは発生する。
* https://github.com/vektor-inc/vk-all-in-one-expansion-unit/commit/d685bbca77f56a11f52e9ed078180f601839991a のコミットが関係している。これを戻すと表示されるようになる。
* CSSカスタマイズのファイルが原因なのにCSSカスタマイズの機能を停止しても改善しない
* 先述の do_blocks( $page_description ) の行をコメントアウトすれば表示される
* 該当データの記事の中の、アイキャッチ画像ブロックを削除すると表示されるようになる

**Comment by drill-lancer** [comment]
マージされたので Close
