### ISSUE TITLE
【お知らせ待ち】広告記事に対する表示機能対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1005]
確か10月くらいから、アフィリエイトの記事とかには 広告 の表示を入れないとあかんようになるっぽい。

とりあえずそのあたりの記事誰か探して、どう実装対応すれば良いか検討お願いしたいっす。

**Comment by drill-lancer** [comment]
- 「記事中に広告貼ってます」という旨の文章を追加してもらう or フックで追加
- 広告の周囲に明らかに広告であることを主張しつつ違和感がないようデザインする

この２択だと思います。

参考：アフィリエイトの ASP のうちの１社の記事
https://www.accesstrade.ne.jp/study/affidai/detail/343

**Comment by kaorock72** [comment]
ひとまず情報を集めてみました

消費者庁：令和5年10月1日からステルスマーケティングは景品表示法違反となります。
https://www.caa.go.jp/policies/policy/representation/fair_labeling/stealth_marketing/

PDF:事業者が講ずべき景品類の提供及び表示の管理上の措置についての指針
https://www.caa.go.jp/notice/assets/representation_cms216_220629_04.pdf#page=16

A8.net：2023年10月施行の景品表示法の指定告示（通称ステマ規制）に関するお知らせ
https://a8pr.jp/2023/08/31/fairlabeling/

バリューコマース：【重要】ステルスマーケティング規制における広告表記に関するお知らせ
https://www.valuecommerce.ne.jp/support/maintenance/19108.html

SWELLは実装してアプデ予定？
https://x.com/ddryo_loos/status/1702594314914931062?s=20

Emanon ProとEmanon Businessでは、9/13のアップデートで機能が追加されました
https://wp-emanon.jp/news/emanon-pro-ver-303/

各テーマのお知らせチェックをしましたが、現時点では関連の通知なし
Snow Monkey、Nishiki Pro、LIQUID PRESS、Cocoon
（Snow Monkey、Cocoonはフォーラムものぞいてみましたが、広告表示については今のところ話題になっていない感じ）

かんたさんのちょっと気になったポスト：data-nosnippet属性を付けてスニペットに反映しないよう指定しています
https://x.com/swell_mania/status/1701917127207436762?s=20

**Comment by drill-lancer** [comment]
@kurudrive 
- `the_content` フックを使って文頭に設置する
- 中身はそれっぽいアイコン＆「本ページはプロモーションを含みます」＆ data-nosnippet 属性を追加
- 設定項目「広告アラート」を設定画面に「投稿タイプ毎」の設定を、各記事の編集画面に「個別記事」の設定を追加

で考えていますがいかがでしょうか？

**Comment by kurudrive** [comment]
@kaorock72 調査ありがとうござます！参考になりました！

@drill-lancer ありがとうございます

> そもそも記事内に広告があるのが紛らわしいし鬱陶しいので廃止（サイドバーとかならタイトルに「広告」と表示すれば良い）

ExUnit の広告挿入機能に関わらず自分で広告を本文中に入れる事があるので、表示機能の追加自体は確定デス。

> the_content フックを使って文頭に設置する
> 中身はそれっぽいアイコン＆「本ページはプロモーションを含みます」＆ data-nosnippet 属性を追加

そうですね。そんな感じで良いかと（・ｗ・ｂ

ExUnit > メイン設定 > PR表記設定
* 表示する文字
* 表示する内容（テキストエリア） 
  この欄に入力がある場合は「表示する文字」は表示されず、こちらに入力した内容に上書きされます。
* 投稿タイプのリストでチェックボックス
* 表示場所（オプション） 
  通常本文の最初に自動的に挿入されます。挿入箇所をアクションフックで指定したい場合はアクションフック名を入力してください。

各個別記事で PR表記設定 のメタボックスを追加して、共通設定を適用 / 表示 / 非表示 をプルダウンで選択可能に

こんな感じですかね。

**Comment by drill-lancer** [comment]
@kurudrive 
Emanon では「表示する文字」が見出しで 「表示する内容」が説明文の役割を持っている感じですが
両方はいらないというお考えでしょうか？

**Comment by kurudrive** [comment]
@drill-lancer あぁ...なるほど...

うーん、いや、いいんじゃないかな。
高度なレイアウトをしたかったらブロックで作って貰えばいいから、ウチとしてもパターンで提供すればいいかなと。

**Comment by drill-lancer** [comment]
走ります

**Comment by kaorock72** [comment]
こちらお知らせ公開とシェア完了しましたので、クローズいたします！
https://www.vektor-inc.co.jp/product-update/exunit9-92-0-0-pr-alert/
