### ISSUE TITLE
【確認待ち】[ 広告アラート ] チェックボックスの表記をスラッグじゃなくてラベル名にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1010]
![スクリーンショット 2023-09-28 1 03 02](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/assets/3272660/98ddc646-17e3-43bc-a20b-d340bcd5967a)

**Comment by drill-lancer** [comment]
マージされたので Close

**Comment by kurudrive** [comment]
![スクリーンショット 2023-10-03 9 00 49](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/assets/3272660/6c119938-2990-4c58-95ad-d91f3b0e92ea)

@drill-lancer ↑これ確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
※ 現状最新の翻訳ではなおっているかもしれないが、それは ExUnit の翻訳が当たっている時点で正しくない。
というのは、投稿タイプのラベル名はフィルターフックなどで改変される場合があるので、 post = 投稿 とは限らない。

**Comment by kurudrive** [comment]
@drill-lancer リリース済みにつき close します。ありがとうございました。
