### ISSUE TITLE
広告アラートのSEO対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1015]
今広告の文字が本文の最初に入る状態だと、SEO面や抜粋などで問題がある。

- [x] 外側のタグを増やして data-nosnippet 属性をつける
- [x] 既存のデフォルト広告アラート及び、独自コードは data-nosnipet のタグの中に入るようにする
- [x] 抜粋欄が未入力の時に desctiption や og:description に広告アラートが入らないようになっているか確認。入る場合は remove_action してから処理するようにするなど対策実施

**Comment by drill-lancer** [comment]
@kurudrive 
data-nosnippet 属性ならすでについていると思います。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/4c6db1566f2ef6c929b0118af26519b3abe09f05/inc/promotion-alert.php#L410

**Comment by kurudrive** [comment]
@drill-lancer マジカヨ！有能 of 有能や！

が、手入力の場合に入らなくなってしまうから、一番外側に div 増やしてそっちに data-nosnippet 属性がつくようによろしくお願いいたします  (￣人￣)

※ もとからそうはなってましたが、元の仕様だと枠線の問題があったので...。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1007

**Comment by drill-lancer** [comment]
@kurudrive 
とりあえずプルリク送りました。
クラス名はいいのが思いつかなかったので適当に修正お願いします。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1016

**Comment by drill-lancer** [comment]
マージされたので Close

**Comment by kurudrive** [comment]
> 抜粋欄が未入力の時に desctiption や og:description に広告アラートが入らないようになっているか確認。入る場合は remove_action してから処理するようにするなど対策実施

↑ よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
問題なかったので Close
