### ISSUE TITLE
構造化データ - WebSite 出力機能新規追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1019]
https://developers.google.com/search/docs/appearance/site-names?hl=ja

* ExUnit > 有効化設定 は デフォルトで true
* alternateName は出力しなくてOK
* is_front_page のみ出力でOKだと思う

**Comment by osmdik** [comment]
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/master/inc/article-structure-data/class-vk-article-structure-data.php

この構造化データとは別でフロントページにのみ適切な構造化データを出力する機能の追加という認識で間違ってないでしょうか？

**Comment by kurudrive** [comment]
ですです。
それは多分個別記事の構造化データ用なので別機能デス。

**Comment by osmdik** [comment]
@kurudrive 
Googleの記事を確認しましたが、下記のような内容で問題ないでしょうか。
```
'@context'      => 'https://schema.org/',
			'@type'         => 'WebSite',
			'name'          => get_bloginfo('name'),
			'url'           => get_bloginfo('url'),
```

**Comment by kurudrive** [comment]
@osmdik 僕もよくわかっていないのでおそらくそれで良いのではないかなと思います（・ｗ・；

**Comment by kurudrive** [comment]
@osmdik 今名前が Front Page になってるけど、よくよく考えたら Google 的には WebSite と言っているのでお手数ですが WebSite に変更してください (￣人￣)
※ クラス名など関連名称諸々...
最優先でよろしくお願いいたします。

**Comment by kurudrive** [comment]
@osmdik ありがとうございました。リリースしましたので close します！

**Comment by kurudrive** [comment]
@kaorock72 製品更新情報に概ね書いてはあります (￣人￣)

**Comment by kaorock72** [comment]
こちらお知らせ公開とシェア完了しましたので、クローズいたします
https://www.vektor-inc.co.jp/product-update/exunit-9-93-0-add-structured-data/
