### ISSUE TITLE
【確認待ち】［SNS Setting］表示場所（オプション）にアクションフック名を入れると、ソーシャルボタンを表示しないにチェックを入れても非表示にならない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#1020]
https://vws.vektor-inc.co.jp/forums/topic/%e8%a1%a8%e7%a4%ba%e5%a0%b4%e6%89%80%e3%81%ae%e3%82%aa%e3%83%97%e3%82%b7%e3%83%a7%e3%83%b3%e3%82%92%e8%a8%ad%e5%ae%9a%e3%81%97%e3%81%a6%e3%81%82%e3%82%8b%e5%a0%b4%e5%90%88%e3%81%a7%e3%82%82%e3%82%bd

Assigneesには石川さんとRickさんを入れさせていただきました🙇‍♀️

**Comment by kurudrive** [comment]
リリース済み

 @drill-lancer ありがとうございました！
