### ISSUE TITLE
［VK プロフィールウィジェット］Twitter のアイコンがXになっていないのかもしれません。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#1037]
以前あげたissueです
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/993

VK プロフィールウィジェットのTwitterのアイコンがXにならない様な気がしました。気のせいだったらごめんなさい。。
![Katawara-愛知県にあるカメラスクール＆スタジオ](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/assets/5525368/7c6f8ede-77f6-42a5-b7a4-c3150e447d47)

Assignees　にはrickさんをいれさせていただきました。お忙しいところすみませんが、ご確認お願いいたします。

**Comment by drill-lancer** [comment]
マージされたので Close
