### ISSUE TITLE
[ シェアボタンブロック ] サイトエディターで「ブロックを空白としてレンダリングします。」にならないようにできないか？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1041]
![スクリーンショット 2023-10-25 14 32 19](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/assets/3272660/e3f95db6-43d3-4d24-b9f4-fb3fc9e02d54)

構造上まぁそうなるわな...とは思いつつも、一般ユーザー視点では ? となってしまうので、見た目だけでも表示されるようにとかできないかな...

**Comment by drill-lancer** [comment]
マージされたので Close
