### ISSUE TITLE
[ カスタム投稿タイプマネージャー ] リライトをオフにするオプションを追加して欲しい by あんどうさん

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1066]
設定 > パーマリンクで /news/%postname%/ にすると
/news/event/%postname%/ になってしまうため

設定画面のチェックボックスでええんちゃう？

**Comment by kurudrive** [comment]
https://gist.github.com/AtsushiA/1e45d176200f70dd23e24c7ebef36957?fbclid=IwAR32wi2rEEF6hhONf-4fDdt6S7X2V_RnX6ZOtnwZr-FX7DRO9ETWQqv0a4Y

**Comment by kurudrive** [comment]
@AtsushiA

* 設定 > パーマリンク設定で /news/%postname%/ にすると他のカスタム投稿タイプのURLにも news がついてしまう
  → 理解
  
  で、ここから  rewrite が true だと、具体的にどういう状態にしたい時に、どう 設定したものが、どうなってしまうかがちょっと理解出来ておらずどう修正してそれが意図した挙動なのか判断できないので改めて記載いただけると助かります (´；ω；｀)

**Comment by AtsushiA** [comment]
@kurudrive 
お手数をおかけしてすみません。
パーマリンクの書き換え (任意) 設定を "パーマリンクを書き換えない"にすると
Custom Post Type Permalinksでパーマリングの変更から該当のポストタイプのパーマリンクが変更できなくなってしまうのです

https://example.com/?[postype]=test-[postname] 固定になってしまう

**Comment by AtsushiA** [comment]
@kurudrive こんな感じだけの設定を変更したいです。以前はこのような感じで対応してました。

`//CustomPostType "news"のフロントでのリライトを無効に変更

function custom_new_permalink( $args, $post_type ) {

if ( 'news' !== $post_type ) {

return $args;

}

$news_args = array(

'rewrite' => array(

'slug' => 'news',

'with_front' => false,

'rewrite_slug' => false,

)

);

return array_merge( $args, $news_args );

}

add_filter( 'register_post_type_args', 'custom_new_permalink', 10, 2 );`

**Comment by torounit** [comment]
with_front を明示的に false にしないと、/news/ が、カスタム投稿のパーマリンクについてしまいますね。

**Comment by kurudrive** [comment]
@AtsushiA 

rewrite の中の 'rewrite_slug' => false, ってこれ true と false で何が変わります？

**Comment by kurudrive** [comment]
@AtsushiA 変更版アップデートしましたんー

**Comment by AtsushiA** [comment]
@kurudrive  ありがとうございます！！確認しました！期待通りでございますm(_ _)m

**Comment by kurudrive** [comment]
_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
