### ISSUE TITLE
X-T9 で Head Title の上書きができていないようです （優先度待ち）

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-all-in-one-expansion-unit#1081]
キャッシュの疑いも確認しましたが、やはり上書きされないようでした。

**Comment by kurudrive** [comment]
@ChiakiKouno Filter Search 側の不具合の影響でしたのでこちらクローズします  (￣人￣)

↓ VK Filter Search 修正版適用したので効いてる状態
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-filter-search-pro/
