### ISSUE TITLE
カスタム投稿タイプ設定からピンのアイコンが他のものに変更できたらと思います

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-all-in-one-expansion-unit#1085]
カスタム投稿がたくさんできた時に見分けがつきやすいように、WordPress標準で用意されているアイコンを管理画面から設定できたらわかりやすい気がします。

例えば以下の「制作実績」をピン以外にアイコンを変えたいと思うことはあります。
![image](https://github.com/vektor-inc/vk-all-in-one-expansion-unit/assets/21466284/27228dd6-c89c-46e9-b677-8670010da622)

ご意見を聞きたく、とりあえず開発の以外の方もAssigneesに入れました。

**Comment by kurudrive** [comment]
@mtdkei ふっふっふ、実装してくれてええんやで (￣ー￣)

**Comment by ChiakiKouno** [comment]
めっちゃくちゃ嬉しい機能ですね！ぜひ実装の方向でどうぞよろしくお願いします！

**Comment by mtdkei** [comment]
@kurudrive @ChiakiKouno 
ご意見ありがとうございます！それでは実装の方向で進めていきます。

**Comment by mtdkei** [comment]
マージされましたのでClose
