### ISSUE TITLE
[ ページ下部お問い合わせ情報 ] HTMLで差し替え機能

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#109]
メイン設定画面／お問い合わせ情報 部分 / "お問い合わせボタンウィジェットに表示するテキスト" の下に

「高度な設定」 ボタン

クリックするとすぐ下に

ページ下部に挿入するお問い合わせ情報を画像で表示する
[     ] [ 画像を選択 ]

ページ下部に挿入するお問い合わせ情報をHTMLで差し替える
[ テキストエリア ] 
画像とHTMLが入力されている場合はHTMLが優先されます

---

画像の選択部分はファビコン設定の所を参考

**Comment by nc30** [comment]
動作しているようです
