### ISSUE TITLE
ExUnit 設定→高速化設定のJavaScriptをフッターで読み込むがオンでVK Blocks Proを1.75.0にすると、初回読み込み時やリロード時間が長くなる

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#1090]
https://vws.vektor-inc.co.jp/forums/topic/exunit-%e8%a8%ad%e5%ae%9a%e2%86%92%e9%ab%98%e9%80%9f%e5%8c%96%e8%a8%ad%e5%ae%9a%e3%82%aa%e3%83%b3%e6%99%82%e3%81%aevk-blocks-pro-1-75-0%e3%81%ae%e6%8c%99%e5%8b%95%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6

> ■ 実際の症状
> いつもお世話になっております。
> 
> ExUnit 設定→高速化設定のJavaScriptをフッターで読み込むがオンになった状態でVK Blocks Proを1.75.0にアップデートすると、読み込みタイミングの影響からか初回読み込み時やリロード時にレイアウトが大きく崩れる時間が長くなり、容易に視認できてしまう状態となります。
> 
> VK Blocks Pro 1.74.0でも若干のタイミングのラグは発生しますが、そこまでは気にならないので許容範囲だと思います。
> 
> なお1.75.0も1.74.0も、ExUnit 設定→高速化設定のJavaScriptをフッターで読み込むをオフにすると症状が出なくなります。※Lightning CSS最適化（高速化）設定は、本件には影響ありませんでした。
> 
> 気付かないままアップデートされる方も多いように思いましたので、ご報告しました。
> 
> ご報告用に画面キャプチャ動画も撮影して編集もしたのですが、レイアウト崩れ時にどうしても色々な情報が見えてしまうので断念しました。。
> 
> ご確認、よろしくお願いいたします。

デモサイトでみたところはそこまでおおきくくずれることはないのですが、オンにした時の方が若干読み込み秒が遅くなるような気はします。（WindowsのFireFoxでも確認）

**Comment by drill-lancer** [comment]
以前廃止しようと思っていたのですが廃止でよいですか？
廃止以外だと結構面倒なことになるので・・・

**Comment by drill-lancer** [comment]
抹殺
