### ISSUE TITLE
[リリース待ち][Google タグマネージャー]iframe要素にtitle属性を追加したほうがよい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-all-in-one-expansion-unit#1091]
アクセシビリティの観点から警告が出るため
↓↓↓
GTMスニペットタグ(noscriptタグ)のiframe要素のtitle属性がない。
https://vws.vektor-inc.co.jp/forums/topic/jis-x-8341-32016

参考:
https://waic.jp/translations/WCAG-TECHS/H64

**Comment by drill-lancer** [comment]
マージされたので Close
