### ISSUE TITLE
【アンケートより：未レビュー】カスタム投稿タイプ設定から解説記事やベクトレへのリンクを追加どうでしょう

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-all-in-one-expansion-unit#1099]
2023年度ユーザーアンケートにて、「カスタム投稿タイプ設定がもう少しわかりやすくなると嬉しい」とのご意見がありました。

すでにわかりやすい記事や動画がありますので、プラグインの画面上のどこかから、それらへのご案内リンクがあると良さそうに思いました。どうでしょうか。

1. ExUnit サイト：[カスタム投稿タイプマネージャー](https://ex-unit.nagoya/ja/about/custom_post_type_manager)
2. ベクトレ：[X-T9 設定ガイド カスタム投稿タイプ編](https://training.vektor-inc.co.jp/courses/x-t9-custom-post-type/)
3. ベクトレ：[Lightning 基本設定解説 カスタム投稿タイプの設定](https://training.vektor-inc.co.jp/courses/lightning-basic-settings/lessons/lightning-custom-post-type-lightning/)

最小限でも 1. ExUnit サイトへのリンクがあると良さそうに思いました。
（他の機能にも言えることかもしれない）

**Comment by mtdkei** [comment]
ありがとうございます。作ってみます！

**Comment by kurudrive** [comment]
|・ｗ・）.oO（ 英語は解説してない or あっても古いので日本語の時だけ表示でよろしくお願いいたします。 ）

**Comment by mtdkei** [comment]
マージされましたのでCloseします。ありがとうございました。
