### ISSUE TITLE
WordFence に上がっている脆弱性対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1100]
https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/vk-all-in-one-expansion-unit/vk-all-in-one-expansion-unit-99810-authenticated-contributor-stored-cross-site-scripting

**Comment by drill-lancer** [comment]
@kurudrive 
いつもなら〇〇の部分に問題があるというメールが来てそうなのですがその情報はなしですか？

**Comment by kurudrive** [comment]
@drill-lancer ないですー。

**Comment by mthaichi** [comment]
@drill-lancer フォームからの全入力において、sanitize_callbackが抜けていないか、必要最低限のHTMLタグしか認めないようになっているかを一つ一つ確認して潰していくしかないですね。
