### ISSUE TITLE
[ VK カテゴリー / カスタム分類リスト ウィジェット ] 昇順・降順を指定できるようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#1115]
![スクリーンショット 2024-10-09 11 25 04](https://github.com/user-attachments/assets/cf69642b-ef35-44ed-9e5f-a18ceeb29d18)

**Comment by mtdkei** [comment]
リリースされていましたのでCloseします。ご作業いただきありがとうございました。
