### ISSUE TITLE
[ WP 6.7 ] 管理画面にエラーが出ている。

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1136]
![image](https://github.com/user-attachments/assets/02e20086-0638-4019-a12c-7fcc02cf33bf)
私の環境だけなのかもしれませんが、管理画面でキャプチャのようなエラーメッセージが出ています。

`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the vk-all-in-one-expansion-unit domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6114 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-admin/includes/misc.php on line 1438 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-includes/functions.php on line 7137 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/functions.php:6114) in /var/www/html/wp-admin/admin-header.php on line 9`

**Comment by kurudrive** [comment]
@akito-38 ありがとうございます。https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1130 で悶絶中です...orz

**Comment by akito-38** [comment]
@kurudrive 
すみません。
そちらにあったんですね。
このissuesはクローズしたらいいでしょうか？

**Comment by akito-38** [comment]
クローズしておきました。

**Comment by kurudrive** [comment]
@akito-38 ありがとうございます (￣人￣)
