### ISSUE TITLE
[ WP 6.7 ] フロント画面にエラーメッセージが出ている

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1137]
![image](https://github.com/user-attachments/assets/b0953b22-dfe8-4fb9-aef4-e64e617dd160)

私の環境だけかもしれませんが、ページを表示すると、キャプチャのようなエラーメッセージが表示されます。

`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the vk-all-in-one-expansion-unit domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/html/wp-includes/functions.php on line 6114`

**Comment by kurudrive** [comment]
related
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1130
