### ISSUE TITLE
[ WP 6.7 ] expansion-unitが有効でテーマがLightningの時、トップページが崩れる

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1139]
![image](https://github.com/user-attachments/assets/a10415a5-31fa-4cad-9d05-da01006658b9)
WP 6.7 で、expansion-unitが有効で、テーマがLightningの時、トップページがキャプチャ画像のようになる。
swiper部分の高さが画面の高さに依存している。

**Comment by mtdkei** [comment]
@akito-38 
ありがとうございます！

issueにしていただいたのにすみませんが、Lightningのトップページスライドの画像の高さですが、swiper部分の高さが画面の高さに依存しているのがここでの仕様となっています。
(以前販売していたLightining Proというテーマでは、以下のようにその旨は明文化されていますが、Lightinig G3の説明ページに書いておいた方がいいかもしれないですね、盲点でした。)
https://lightning.vektor-inc.co.jp/lightning-pro/setting/basic/top-slide#:~:text=%E7%94%BB%E5%83%8F%E3%81%AF%201900px%20x%20600px%20%E3%82%92%E6%8E%A8%E5%A5%A8%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82%E3%81%99%E3%81%B9%E3%81%A6%E3%81%AE%E7%94%BB%E5%83%8F%E3%81%AE%E9%AB%98%E3%81%95%E3%82%92%E6%8F%83%E3%81%88%E3%81%A6%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82

その上でですが、確認したいことがございます。
Lighitningを入れた時点で高さの違う画像2枚がデフォルトで入ってしまっている状態でしたでしょうか？
ご確認くださった時の状況をそろえて、まっさらな状態でLightiningを入れてみたのですが、こちらで確認する限りでは以下のようになりましたので、もし再現手順等ありましたら書いていただけたら幸いです。
![image](https://github.com/user-attachments/assets/ec6d9bfb-4a3d-46b7-9f87-6ae763db9ec4)

@kurudrive 
念のためですが、今でもLightningのトップページスライドでは、swiper部分の高さ=画像の高さですよね？

**Comment by akito-38** [comment]
@kurudrive @mtdkei 
すみません。確認ありがとうございます。
WPのリリースバージョンで改めて確認してみたら問題無さそうです。
画像は、Lighitningを入れた時点でデフォルトの同じ高さの画像が2枚です。
それでキャプチャのようになっていました。
もしかしたら確認したベータ版特有の現象だったのかもしれません。

石川さんの質問にご回答いただいたらクローズしていただいて問題無いと思います。
