### ISSUE TITLE
[ WP 6.7 ] expansion-unitが有効の時、パラグラフブロックのサイドバーに属性という項目が追加される。

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1140]
![image](https://github.com/user-attachments/assets/bee329e2-ab54-485d-ba7c-e129eb001d82)
![image](https://github.com/user-attachments/assets/553691e7-d177-4e3b-b565-753bac84a54c)

**Comment by mthaichi** [comment]
@kurudrive  @akito-38 これは6.7から追加された公式の機能なので、このままで良いかと思いますが、いかがでしょう。

https://www.prime-strategy.co.jp/column/archives/column_9022#%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%83%90%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%82%92%E7%9B%B4%E6%8E%A5%E5%A4%89%E6%9B%B4%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB

**Comment by kurudrive** [comment]
@mthaichi @akito-38 はい、不具合というわけでもないですしこのままで良いと思いますので一旦closeします。
ありがとうございます  (￣人￣)

**Comment by akito-38** [comment]
@kurudrive @mthaichi
確認ありがとうございます。
一応私の所見として、

・expansion-unitが動いてない場合は表示されない。
・どうやって使うのかわからない。

という事だけ記しておきます。
