### ISSUE TITLE
[ WP 6.7 ] expansion-unitが有効の時、カテゴリの選択欄が伸びる

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1141]
![image](https://github.com/user-attachments/assets/4537b7f2-5f26-4511-ac1a-78b63545ef7d)

投稿詳細でカテゴリの選択欄がすごく伸びている。

**Comment by kurudrive** [comment]
@akito-38 確認ありがとうございます。
僕の環境では発生しなかったのですが、これは ExUnit のCSSの干渉によるものでしょうか？
原因などあたりがつきそうならプルリクよろしくお願いいたします。

**Comment by akito-38** [comment]
@kurudrive 
わかりました。
対応してみます。

**Comment by akito-38** [comment]
@kurudrive 
すみません。
今確認してみたところ大丈夫そうです。
ナイトリーだけの現象だったのかもしれません。
クローズしておきます。
