### ISSUE TITLE
[ WP 6.7 ] expansion-unitが有効の時、カスタマーザーがのサイドバーが崩れる

### ISSUE THREAD

**Issue by akito-38** [vektor-inc/vk-all-in-one-expansion-unit#1143]
![image](https://github.com/user-attachments/assets/97e77ae8-4730-478b-8724-dde0b82b84cb)
添付画像のように縦伸びします。
Twenty Fifteen とlightningで確認しましたが、どちらもなっていました。

**Comment by mtdkei** [comment]
@akito-38 
ありがとうございます。
こちらでも同様の現象を確認いたしましたが、こちらの環境では特定の環境のみで発生し、複数の異なる環境では再現しないことがほとんどでした。
#1141 でも同様の挙動が確認され、この問題が発生する環境では再現するものの、発生しない環境では #1141 も発生しないようです。もしかしたら他にも上げていただいたissueで同様の事象が発生するかもしれません。

気になって調査を進める中で、このissueなどの現象が発生する環境では wp-config.php 内の

```
if ( ! defined( 'WP_DEBUG' ) ) {
	define( 'WP_DEBUG', true );
}

```

のようにデバッグモードが有効な場合にissueのような現象が起きていることがわかりました。デバッグモードを false に設定してみたところ、問題が再現しなくなりました。

もしかしますが同様のケースかもしれませんので、もしよろしければこちらをご確認いただければ幸いです。

**Comment by akito-38** [comment]
@mtdkei 
確認ありがとうございます。
承知しました。
では、そのように進めてみます。

**Comment by akito-38** [comment]
@mthaichi 
![image](https://github.com/user-attachments/assets/b25fe173-6a67-47da-967c-0fb39bfb43ee)

Warning: Undefined array key "default" in /var/www/html/wp-includes/option.php on line 3177
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-includes/option.php:3177) in /var/www/html/wp-admin/customize.php on line 130

デバッグモードだとbody直下に画像のようなエラーメッセージが入ってますね。
これが原因でCSSが正しく機能してないのが原因ぽいです。
他の部分もおそらく同様の原因ですね。

**Comment by kurudrive** [comment]
@akito-38 ありがとうございますー。その件は今直してます−。ちなみに ExUnit > 有効化設定 を一度保存するとそのエラーは出なくなります−ん。

**Comment by akito-38** [comment]
@kurudrive 
ありがとうございます。
やってみましたがだめでした。
でも直していただいてるなら問題無いですね。

**Comment by kurudrive** [comment]
9.100.4 にアップデートしたらエラーはでなくなると思いますがどうでしょう？

**Comment by akito-38** [comment]
@kurudrive 
アップデートしてみましたが、ダメでした。

**Comment by kurudrive** [comment]
うーむ、僕の環境でいくつか見てるけど再現しない...（・ｗ・；
なんだろうねぇ...。

**Comment by mtdkei** [comment]
@kurudrive 
こちらも現象が発生する箇所では同様です。プラグインを全て停止しても同様でした。
Lightiningから別のテーマに切り替えたらこのissueの現象はなくなりましたが、 @akito-38 さんのケースではテーマは関係なさそうでしたのでなんともわかりません。

**Comment by akito-38** [comment]
@kurudrive @mtdkei 
改めて確認してみたところ、私も同様にプラグインを全て停止してもこの事象は起こりました。
Lightiningから別のテーマに切り替えたらこのissueの現象はなくなりました。

最初確認した時は、別のテーマに切り替えても改善されませんでしたが、アップデートによってプラグイン側のエラーメッセージが無くなった為ではないかと推測します。

**Comment by goutetsuguma** [comment]
私のローカルでもデバッグモードを有効にして確認しましたら、Lightning (masterブランチ)とExUnit(masterブランチ)の時に同様の症状が確認できました。
私の環境では以下のエラーが出ていました。

` ( ! ) Notice: 関数 _load_textdomain_just_in_time が<strong>誤って</strong>呼び出されました。<code>lightning</code> ドメインの翻訳の読み込みが早すぎました。これは通常、プラグインまたはテーマの一部のコードが早すぎるタイミングで実行されていることを示しています。翻訳は <code>init</code> アクション以降で読み込む必要があります。 詳しくは <a href="https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/">WordPress のデバッグ</a>をご覧ください。 (このメッセージはバージョン 6.7.0 で追加されました) in /Users/goutetsuguma/Local Sites/testsite/app/public/wp-includes/functions.php on line 6114`

**Comment by kurudrive** [comment]
@akito-38 @mtdkei @goutetsuguma 
Lightning と ExUnit は _load_textdomain_just_in_time のエラーが出ないように最新版では修正されてるので、どちらかが古いバージョンだと発生するとは思います。
両方最新だと僕の環境では再現しない状態です（・ｗ・

**Comment by akito-38** [comment]
@kurudrive  @mtdkei @goutetsuguma
Lightningが最新バージョンでも発生してました。

しかし、Lightningを管理画面から一回削除して再インストールしてみたところ改善させれました。

**Comment by kurudrive** [comment]
こちらもう発生しないと思いますので close します。
また発生していましたら open してください (￣人￣)
