### ISSUE TITLE
[ WP 6.7 ] ExUnit > CSSカスタマイズで入力したCSSが出力されない

### ISSUE THREAD

**Issue by mtdkei** [vektor-inc/vk-all-in-one-expansion-unit#1145]
ダッシュボードから  ExUnit > CSSカスタマイズ に移動し、そこでCSSを書いて保存しました。
例では.entry-headerを見えなくするようにしています。
![image](https://github.com/user-attachments/assets/38929f2a-86c5-487b-aef0-9e36a67ea761)

個別記事を確認したのですが、タイトルや日付等が見えている状態でした。
entry-headerでページ内検索をしてもHTMLのクラス名、entry-headerしか出力されていないので、おそらくCSSが出力されていないものとおもわれます。
![image](https://github.com/user-attachments/assets/25852508-66bb-47a0-aec3-101f91388b31)
![image](https://github.com/user-attachments/assets/c5a3708a-d16e-4b04-b14a-9bb8f5af3a38)

個別記事の編集画面にあるExUnitのCSSカスタマイズは出力されていました。
![image](https://github.com/user-attachments/assets/07a12e78-16f1-4113-b64e-a256493059e1)
![image](https://github.com/user-attachments/assets/af66601f-782f-49ae-8504-5ef37f9c7931)

 ExUnit > CSSカスタマイズのCSSはアップデート前(ver.9.99あたり)までは出力されていました。

**Comment by kurudrive** [comment]
これが関係するかも
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/1142

**Comment by kurudrive** [comment]
これ僕がインしたら（11時頃）やります（・ｗ・
その前に誰かやる場合はアサインを切り替えてから着手してくださいー。

**Comment by kurudrive** [comment]
リリース済みなので close します。ありがとうございました！
