### ISSUE TITLE
[ 投稿ループ前ウィジェットエリア ] 有効化して、ウィジェットの投稿タイプアーカイブのループ前 ウィジェットにブロックを入れても表示されない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#1147]
投稿ループ前ウィジェットエリアは有効化して、投稿タイプアーカイブのループ前 （投稿）に何かブロックを入れても、アーカイブページで入れた内容が表示されないようでした。

https://vws.vektor-inc.co.jp/forums/topic/exunit%e3%80%8c%e6%8a%95%e7%a8%bf%e3%83%ab%e3%83%bc%e3%83%97%e5%89%8d%e3%82%a6%e3%82%a3%e3%82%b8%e3%82%a7%e3%83%83%e3%83%88%e3%82%a8%e3%83%aa%e3%82%a2%e3%80%8d%e3%81%ae%e7%99%bb%e9%8c%b2%e5%86%85

**Comment by kurudrive** [comment]
確認しまする

**Comment by kurudrive** [comment]
@goutetsuguma リリースしましたので close いたします。
ありがとうございました！
