### ISSUE TITLE
WPXサーバー対策として

### ISSUE THREAD

**Issue by bbfriend** [vektor-inc/VK-All-in-One-Expansion-Unit#150]
ｗｐＸサーバー（　https://www.wpx.ne.jp/server/　）　の仕様で、
/wp-content/plugins/ や　/wp-content/themes/　より下位に　pluginsディレクトリは作成できません。
ですので、
wp-content/plugins/vk-all-in-one-expansion-unit/**plugins**　を　持つこと（アップロード）ができません。
・・別名でＵＰして　その後のリネームも出来ません

plugins_all  や　plugins_　などに変更できますか？？

PS)　lightning-advanced-unit　も　pluginsディレクトリを持ってますので　こちらも　(o*｡_｡)oﾍﾟｺｯ

**Comment by kurudrive** [comment]
@bbfriend

Oh...それは問題ですね...
wpX利用されてる方多いと思いますので、早急に対策したいと思いますが、いろいろ立て込んでおりましてすぐには手が出せないのですが、何とか今週中を目処に調整する予定です。
恐れいりますが今しばらくお待ち願います...

**Comment by bbfriend** [comment]
ありがとうございます。
作成できないのは、FFFTP等でのFTP転送で、管理画面からの新規プラグインインストールは問題ありません。ユーザー権限の関係で規制されてます。

このwpXの規制は、サーバーの移転・引っ越しや、wordpress.org/ 以外の非公式系のUPの際に気づきます。

**Comment by kurudrive** [comment]
https://github.com/kurudrive/lightning-advanced-unit/commit/bcf1d37077b5e0d8f3dc651c29418c273c53f8e6

**Comment by kurudrive** [comment]
68440a2a0369e16ffa5381a96ace142caf84d239
313564b8f606e99df0add5011536b22c87fb4c05

**Comment by kurudrive** [comment]
9.0.0に反映済み
