### ISSUE TITLE
[ 最新の記事ウィジェット ] 更新日順 が選択出来るように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#153]
現状で公開日順にしかならない。
- 公開日順
- 更新日順

の選択ラジオボタンをつけて、更新日順でも表示出来るようにする。

更新日順になっている場合は、表示する日付を 
get_the_modified_date()
で表示するようにする。
#### 対象ファイル

/vk-all-in-one-expansion-unit/plugins/other_widget/widget-new-posts.php

**Comment by nc30** [comment]
@kurudrive 
 #153

**Comment by kurudrive** [comment]
あざっす！
