### ISSUE TITLE
[ バナーウィジェット ] メディアのタイトルと代替テキストが反映されるように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#180]
<del>メディアアップローダーでアップする時に「タイトル」と「代替テキスト」を入力する項目があるが、この内容が img タグの titile と alt に反映されるようにする</del>

代替テキスト の入力欄を画像選択ボタンの下に追加し、altに反映されるようにする。

**Comment by nc30** [comment]
@kurudrive #185
