### ISSUE TITLE
[ 機能追加 ] 推奨外バージョンのPHP使用時のプラグイン無効化

### ISSUE THREAD

**Issue by nc30** [vektor-inc/VK-All-in-One-Expansion-Unit#192]
サポートが終了しているのPHPを使用している場合、動作を停止させる。

http://php.net/supported-versions.php

- 名前空間の使用は今後使用するので5.3.0より下は使用不可。
- 実際のところ**5.5以下**はすでに**サポート対象外**なのでプラグインも使用停止したいが、ホスティング会社の未対応等やむを得ない事情を考慮し、5.4.45以上は警告は出すが使用可能とする。
- サポート対象である5.6以上は警告もなく今までどおり使用できる。

これ以上緩めるのは危険です

**Comment by kurudrive** [comment]
@nc30 コメント調整したっす。
