### ISSUE TITLE
「行動を促すためのお問い合わせ先表示」が投稿ページ下部にも表示される

### ISSUE THREAD

**Issue by nnamm** [vektor-inc/VK-All-in-One-Expansion-Unit#205]
加えて、固定ページの編集画面にある「お問い合わせ情報の表示」のチェックボックスのON/OFFに関わらず表示されます。

どのような情報があれば調査できるのか、教えていただければお伝えいたします。
なお、自分のサイトはこちらです。 → http://nnamm.com

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
修正版アップしましたのでご確認よろしくお願いいたします。

**Comment by nnamm** [comment]
早速の対応ありがとうございます。
正常に機能することを確認しましたが、一部で挙動がおかしいです。
以下の場合は、お問い合わせが投稿ページ、固定ページ（表示のON/OFFに関わらず）に表示されます。

VK All in One Expansion Unit 有効化設定 → 拡張機能 → extention contentsの「ループ終了時にコンテンツを追加する」がON

当方、ON/OFFの意味はわかっていません。たしか、プラグインのインストール時はデフォルトでOFFだった記憶があります。OFFにしておいた方が良いでしょうか。

**Comment by kurudrive** [comment]
ご報告ありがとうございます。
機能の意味としては通常は『本文に該当する内容の一番下に含めて出力』しているのですが、
ループ終了時というのは 『本文に該当する内容の後に出力』する機能で、後から試行錯誤しながら追加実装しているのですが、現状ではやはりまだ動作が不安定なようで...
OFFでの運用をお勧めしています。
ご迷惑おかけしますがよろしくお願いいたします。

**Comment by nnamm** [comment]
OFFでの運用ですね、了解しました。
OFFにしていれば、しっかり動作していますので大丈夫です。

ありがとうございました！
