### ISSUE TITLE
【カスタム投稿タイプ設定】投稿タイプIDを小文字半角英数字に自動変換させる

### ISSUE THREAD

**Issue by catherine87** [vektor-inc/VK-All-in-One-Expansion-Unit#253]

**Comment by catherine87** [comment]
大文字で入力されるとエラーになって正しく動作しないため。

**Comment by catherine87** [comment]
@kurudrive 

下記対応しました。確認お願いします。

・小文字、半角に自動変換
・２０文字以上だったら強制的に丸める

ブランチ　origin/#253-ptm　です。

**Comment by catherine87** [comment]
@kurudrive 

よくわかりませんが、何か大丈夫そうな気がします。

origin/#253-ptm　で確認お願いします。

**Comment by catherine87** [comment]
@kurudrive 

プッシュしました。
確認お願いします。

**Comment by kurudrive** [comment]
ブルリクしといてー

2018年4月25日(水) 8:32 catherine <notifications@github.com>:
