### ISSUE TITLE
Deprecated: The each() function is deprecated.

### ISSUE THREAD

**Issue by hideokamoto** [vektor-inc/VK-All-in-One-Expansion-Unit#288]
In php7.2, there are deprecated messages when your plugin activated.

```
Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /var/www/html/web/wp/wp-content/plugins/vk-all-in-one-expansion-unit/plugins/call-to-action/class-vk-call-to-action.php on line 92
```

https://wiki.php.net/rfc/deprecations_php_7_2#each
https://qiita.com/rana_kualu/items/db1ce401df627c46544a#the-each-function-has-been-deprecated

**Comment by kurudrive** [comment]
Thaaaaaaaaaaaaaaaaaaaaaaaaaank Yooooooooooooooooooooooooooooooooou
Sooooooooooooooooooooooooooo Muuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuch!!
