### ISSUE TITLE
[ GA設定 ] カスタマイザー実装

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#298]

**Comment by catherine87** [comment]
カスタマイザーの項目少ないですけど、
ファイル構造を統一したいので（plugins/google_analytics/ga_customizer.php）を追加して作業してます。

**Comment by kurudrive** [comment]
うん、こうやって自分で必要な機能改善を見つけて進めてくれるととても有り難いです！

**Comment by catherine87** [comment]
@kurudrive 

ありがとうございます~
で、で、で、なんとなくできてプッシュしたいのですがソースツリーが...ugokimasen!

**Comment by catherine87** [comment]
@kurudrive 

プッシュしました。
確認お願いします。

**Comment by catherine87** [comment]
これ今どうなってるんでしたっけ？

**Comment by kurudrive** [comment]
確認待ちです ＞＜

**Comment by catherine87** [comment]
あ、すみません、slackとの連携テストコメントでしたww

**Comment by kurudrive** [comment]
ごめん、これどのブランチだっけ...（・ｗ・？

**Comment by catherine87** [comment]
@kurudrive 

#298
でブランチきってやったんですが、何か変かもですー...

**Comment by kurudrive** [comment]
ありがとー。機能としてはいいんじゃないかと思います。
翻訳がカスタマイザーの方で効いてないのは何でだろう...ExUnitのメイン設定と同じ文面持ってきてるんだよね？
まぁDevelopにマージしてpoファイルからmoファイル出力しなおしたら効くような気もしますが（・ｗ・

**Comment by catherine87** [comment]
@kurudrive 

基本すべてコピペで行うようにしています。
ですが、表示する範囲が狭いので見やすくするために <br>タグを追加したり、入力欄の上下で分かれていたものを一箇所にまとめたりすることで、同じ文章とはみなされず翻訳する必要が出てくるようです。

マージ後最後に翻訳するということなので、確認いただいたあとに同じ日本語訳を追加するつもりでした。
もし、同じ内容が翻訳ファイル内に存在するのが都合が悪いということがあれば、改修しますのでよろしくお願いします。

**Comment by kurudrive** [comment]
@catherine87 
closeしまする。ありがとーう。
