### ISSUE TITLE
GoogleAnalytics の gtag.js 対応

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#318]
https://forum.vektor-inc.co.jp/forums/topic/gtga/

### 現状

* ユニバーサル アナリティクスのコードを出力します。( デフォルト )
*  ノーマルのコードのみを出力します。
*  両タイプのコードを出力します。

### 変更後

* 推奨（gtag）
* ユニバーサル アナリティクスのコード（analytics.js）
* ノーマルのコード（analytics.js）

※ 選択が無い場合は gtag を出力

### 参考
https://developers.google.com/analytics/devguides/collection/gtagjs/?hl=ja
http://www.kagua.biz/help/config/gtagjs.html

**Comment by catherine87** [comment]
【メモ】デフォルト値の設定を確認する
