### ISSUE TITLE
本文したにウィジェットエリアをフックで挿入出来るかテスト

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#33]
現状いろいろフックで本文下に出力したいが、順番を自由に入れ替えられないので、そもそも本文下にウィジェットエリアをフックで挿入すれば可能だと思うので・・・。
テーマに最初から設定すれば便利だが、プラグインで実現したいので。

**Comment by nc30** [comment]
ループ終了直後に追加することは出来ました
