### ISSUE TITLE
[ サイトマップ ] サイトマップに表示したくないページを固定ページから直接指定出来るように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#332]
シェアボタンは 各投稿記事の編集画面で、チェックを入れると表示されなくなる機能がある
同様にサイトマップに表示しない のチェックボックスを設置。

チェックをいれられたもをサイトマップ一覧から除外する。

**Comment by kurudrive** [comment]
@catherine87 あれ、これってマージしたっけ？

**Comment by catherine87** [comment]
@kurudrive 
すみません、こちらでは把握できていません。

おそらくまだされていないかと思いますが...

**Comment by kurudrive** [comment]
ブランチはどれになる？
実装自体は完了してたっけ？
なんとなくエニシアで動作確認してたような記憶はあるけど...
問題なく動作してたらプルリク出しておいて〜。

**Comment by kurudrive** [comment]
Close ... (￣人￣)
