### ISSUE TITLE
[ ページ固有のカスタムCSS機能 ] 新規追加 

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#341]
個別の固定ページや投稿ページ専用のCSSを記載、反映される機能を追加する。

コードを書く手法としては下記にも紹介されている。

https://webnetamemo.com/coding/wordpress/201708115484

※ 上記のやり方だとエスケープなど問題もありそうなので、出力時の処理は再考する必要がある。
本当は add_linline_styleが望ましいが 依存対象cssはテーマ毎に違うので wp_head の後ろに方に指定するしかないかも...。まぁそのあたりの最終調整は石川が行う...と思う。

vk-all-in-one-expansion-unit/plugins/css_customize/css_customize_single.php を新規作成してそこに処理を書く。
vk-all-in-one-expansion-unit/plugins/css_customize/css_customize.php から上記ファイルを読み込む。

* まずは固定ページや投稿ページにmetaboxを作成。
* そのmetaboxにカスタムフィールドでテキストエリアを作成する。
* カスタムフィールドに入力された値の保存処理を書く。
* 保存されている内容をwp_headに出力する。
 
追記 : CSSの出力は `wp_head`  に `wp_kses_posts() ` くらいで良いす。
出力順はExUnit標準（共通）のCSSカスタマイズの後ろで

**Comment by kurudrive** [comment]
@catherine87 
追記 : CSSの出力は `wp_head`  に `wp_kses_posts() ` くらいで良いす。
出力順はExUnit標準（共通）のCSSカスタマイズの後ろで

**Comment by catherine87** [comment]
[ 修正メモ ]
プリフィックスをつける

**Comment by kurudrive** [comment]
@catherine87 

対象が 投稿 と 固定ページ だけだったので、カスタム投稿タイプにも自動で対応するように変更しました。時間のある時にコード見ておいてください。

https://github.com/vektor-inc/VK-All-in-One-Expansion-Unit/commit/28181503ea25751a3f1b1b079fbc119876191939
