### ISSUE TITLE
フッターのコピーライトの ExUnit のリンク先がおかしい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/VK-All-in-One-Expansion-Unit#343]
Lightning のフッターのコピーライトは ExUnitから  書き換えられている。
ExUnit の部分のリンク先がおかしい。
もしかしたら英語版は問題なくて翻訳ファイルがおかしいのかも。

**Comment by naogify** [comment]
@kurudrive 日本語の翻訳ファイルがおかしかったので、再コンパイル中なのですが下のようなエラーがでます、、。もしエスケープの方法知っていれば教えてもらえると嬉しいですー！

<img width="360" alt="2018-08-03 10 57 09" src="https://user-images.githubusercontent.com/8760841/43620130-304db5d0-970c-11e8-9efb-a61e4d800d4b.png">

**Comment by naogify** [comment]
↑上の問題解決しました！

**Comment by kurudrive** [comment]
ありがとうございました！
