### ISSUE TITLE
[ Gutenberg Blocks ]のPR Contentで「高度な設定→追加CSSクラス」が反映されない

### ISSUE THREAD

**Issue by yamasakidaisuke** [vektor-inc/VK-All-in-One-Expansion-Unit#383]
いつもありがとうございます。多方面で使わせてもらっており感謝しております。
表題のとおりです。他のブロックスは反映されました。ご確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
@naogify 確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
@yamasakidaisuke Block関連修正・調整に苦戦してまして明日リリース予定です ＞＜

**Comment by yamasakidaisuke** [comment]
ご対応ありがとうございます。バージョン 7.9.1 にて直っていないように思いました。まだ対応中かもしれませんが、よろしくお願いいたします。

**Comment by kurudrive** [comment]
かなり大掛かりな変更をしたのですが、ExUnitはユーザー数が多くていきなりリリースは影響範囲が大きそうなので、単独プラグインの方で先行リリースにしました。
お急ぎの場合は ExUnit の VK Blocks を停止して、単体プラグインの VK Blocks でご確認いただけると助かります。
https://www.vektor-inc.co.jp/info/vk-blocks-0-7-0/?rel=vkadmin

**Comment by yamasakidaisuke** [comment]
だいぶご苦労されておりますね。ご丁寧にありがとうございます！

**Comment by yamasakidaisuke** [comment]
https://www.vektor-inc.co.jp/info/vk-blocks-0-7-0/?rel=vkadmin
誤字がございました。私は気になりませんがお伝えいたします。
最後のアラート文章です。
「そお際は」になっておりました。

**Comment by yamasakidaisuke** [comment]
> 
> 
> かなり大掛かりな変更をしたのですが、ExUnitはユーザー数が多くていきなりリリースは影響範囲が大きそうなので、単独プラグインの方で先行リリースにしました。
> お急ぎの場合は ExUnit の VK Blocks を停止して、単体プラグインの VK Blocks でご確認いただけると助かります。
> https://www.vektor-inc.co.jp/info/vk-blocks-0-7-0/?rel=vkadmin

 ExUnit の VK Blocks を停止して、単体プラグインの VK Blocks　にて、改善いたしました！ありがとうございます。

**Comment by kurudrive** [comment]
報告ありがとうございました！
ExUnitの方でも反映してありますのでcloseいたします。
また何かありましたらよろしくお願いいたします。

**Comment by yamasakidaisuke** [comment]
ご対応ありがとうございます！
今後ともよろしくお願いいたします。
