### ISSUE TITLE
[ CSSカスタマイズ ] のエスケープ

### ISSUE THREAD

**Issue by xakuro** [vektor-inc/VK-All-in-One-Expansion-Unit#385]
CSS カスタマイズの「>」(子セレクタ) が「&amp;gt;」に変換されてしまいます。
wp_kses_post() ではなく strip_tags() などのほうがいいのではないでしょうか。WordPress のフォーラムにも書き込みをしましたのでご参照いただければと思います。
https://ja.wordpress.org/support/topic/lightningでフォント変更が反映されなくなった/#post-234383

**Comment by xakuro** [comment]
対応ありがとうございました。

**Comment by kurudrive** [comment]
@xakuro 報告ありがとうございました！
ちょっと別の修正分が手こずってまして、その分と併せて明日アップデート予定です ＞＜
