### ISSUE TITLE
template-tags のエラー

### ISSUE THREAD

**Issue by gold1** [vektor-inc/VK-All-in-One-Expansion-Unit#389]
【現象】
トップページで以下のエラーが表示される。

Notice: Trying to get property 'taxonomy' of non-object in /var/www/vhosts/jncvd-achd.wdc-jp.com/httpdocs/wp-content/plugins/vk-all-in-one-expansion-unit/plugins/template-tags/template-tags.php on line 68

Notice: Trying to get property 'object_type' of non-object in /var/www/vhosts/jncvd-achd.wdc-jp.com/httpdocs/wp-content/plugins/vk-all-in-one-expansion-unit/plugins/template-tags/template-tags.php on line 69

表示されている投稿が１件以上になるとエラーは消えました。
もしくは、管理者画面にログインしているときもエラーは消えました。

【実行環境】
* CentOS7.3   64bit
* Apache   2.4.6
* PHP 7.2
* WordPress 5.1.1
* テーマ Lightning
* VK All in One Expansion Unit 8.0.2

【実行手順】
・WordPress をインストール
・wp-config.php で define('WP_DEBUG', true); を設定する。
・プラグインをインストール
・元々投稿されていた記事を非表示にする。この時点で表示されている投稿が０件。
・管理者画面からログアウトする。

【コメント】
私自身はWP にあまり詳しくありません。

**Comment by kurudrive** [comment]
ご報告ありがとうございました！
