### ISSUE TITLE
管理画面の挙動がおかしいです。

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/VK-All-in-One-Expansion-Unit#408]
管理画面の設定部分の挙動がおかしいです。
フォーラムにも記載しておきました。
https://vws.vektor-inc.co.jp/forums/topic/vk-all-in-one-expansion-unit%E3%81%AE%E3%82%A8%E3%83%A9%E3%83%BC

**Comment by kurudrive** [comment]
本件開発中の最新版（ https://github.com/vektor-inc/VK-All-in-One-Expansion-Unit/tree/develop ）では修正済みですのでcloseします。
いつもありがとうございます。
