### ISSUE TITLE
WooCommerceでの不具合

### ISSUE THREAD

**Issue by ifNoob** [vektor-inc/vk-all-in-one-expansion-unit#416]
以前にExUnit不具合で修正されたと思う、smooth-scroll.js 内の
$('body,html').animate({scrollTop:position}, speed, 'swing');
return false;
            ↑
9.1.4も、同じとなっており、falseは必要ないと思いますが、
WooCommerce以外でのスクロールにて使われている事から、false は要るのかは?。

**Comment by kurudrive** [comment]
環境用意して動作確認しましたが、タブは問題なく開きました。

前回指摘を受けて 9.3.1 の時点で既に指摘の false は修正済みですので、
現状の 9.4系はタブの動作はするはずですのでご確認よろしくお願いいたします。

https://github.com/vektor-inc/VK-All-in-One-Expansion-Unit/commit/f3287446d774d63654e51969973177692574181d
