### ISSUE TITLE
ExUnitブラグイン SNS内の関数

### ISSUE THREAD

**Issue by ifNoob** [vektor-inc/VK-All-in-One-Expansion-Unit#417]
function_snsBtns.php 内の
add_action( 'wp_ajax_vkex_pocket_tunnel', 'veu_sns_pocket_tunnel' );
add_action( 'wp_ajax_nopriv_vkex_pocket_tunnel', 'veu_sns_pocket_tunnel' );
以下 function veu_sns_pocket_tunnel() {
この関数群は必要?。
開発用プラグイン、Query MonitorにてPHP Error出力してます。

**Comment by kurudrive** [comment]
こちらは該当開所削除しましたのでCloseします。
次回バージョンアップまでお待ちください。
報告ありがとうございました。
