### ISSUE TITLE
挿入アイテムの設定が表示されない

### ISSUE THREAD

**Issue by saulks** [vektor-inc/VK-All-in-One-Expansion-Unit#422]
バージョン9.6.0.1でも、HTMLサイトマップの表示を有効にしないと、他オプション（子ページ、先祖ページ、お問い合わせ）を有効にしても、挿入アイテムの設定が表示されません。

**Comment by kurudrive** [comment]
おや...おかしいですね...
以前はたしかに再現したのですが、先日テストも書いて修正して解消したので僕の環境では再現しないのですが、確認している投稿タイプは何ですか？

**Comment by kurudrive** [comment]
ご利用のWordPrennのバージョン？
投稿？固定ページ？その他のカスタム投稿タイプですか？

**Comment by saulks** [comment]
WordPress 5.2.3 (Lightning テーマ)いずれも最新です。
画像のような設定で挿入アイテムの設定が表示されません。

![Screen Shot 2019-09-08 at 23 00 25-fullpage](https://user-images.githubusercontent.com/54830111/64489362-1e2d0780-d28d-11e9-8268-56a1ec006722.png)
![Screen Shot 2019-09-08 at 23 00 44-fullpage](https://user-images.githubusercontent.com/54830111/64489361-1d947100-d28d-11e9-93e6-3975a6e910f2.png)

**Comment by kurudrive** [comment]
今日あるいは明日リリースのバージョンで修正済みにつき一旦closeします。
報告ありがとうございました。
