### ISSUE TITLE
[ サイトマップ ]カスタム投稿毎に表示・非表示を可能に

### ISSUE THREAD

**Issue by rick-addison** [vektor-inc/VK-All-in-One-Expansion-Unit#423]
フォーラムでサイトマップに関するトピックが立っています。
要はカスタム投稿毎に表示・非表示を可能にして欲しいとのことです。
https://vws.vektor-inc.co.jp/forums/topic/サイトマップについて

**Comment by kurudrive** [comment]
実装＆リリースしましたー。
