### ISSUE TITLE
OGP設定で、og:imageにog:image:width,og:image:heightの追加について

### ISSUE THREAD

**Issue by tomhat** [vektor-inc/VK-All-in-One-Expansion-Unit#430]
いつもありがとうございます。

本日OGP設定を行い、こちらのFacebookのデバッグツールで確認したところ。
https://developers.facebook.com/tools/debug/sharing/

og:image:width,og:image:heightの指定のエラーが出ていました。
こちらog:imageタグ出力時に追加できないでしょうか？

**Comment by kurudrive** [comment]
エラーのキャプチャは貼れますか？

**Comment by tomhat** [comment]
![Uploading 貼り付けた画像_2019_10_18_4_59.png…]()
御連絡ありがとうございます。こちらになります。

**Comment by tomhat** [comment]
御連絡ありがとうございます。
こちらになります。

https://gyazo.com/fb8daf58522cdb59727f8e2593a8f19a

**Comment by kurudrive** [comment]
もう一度スクレイピングをクリックしてみてください。

**Comment by kurudrive** [comment]
一番最初にFacebookが読み込む時の現象ですね。
僕としては

* 初回のみなので「もう一度スクレイピング」をクリックするか、２回目以降FacebookにURLを貼る分には問題ない
* 対応しようとするとおそらくjsで処理しないといけないから表示パフォーマンスが落ちる
* 上記踏まえてあまり重要性を感じないので、ここの対応するよりももっと便利なブロック開発などした方がユーザーメリットが大きい

という理由でExUnitでは対応を予定していません。
ごめんなさい ＞＜

どうしてもという場合はExUnitのOG出力を停止して他のSNSプラグインにてよろしくお願いいたします。 m（Ｔ−Ｔ）ｍ

**Comment by tomhat** [comment]
返信ありがとうございます。

> 対応しようとするとおそらくjsで処理しないといけないから表示パフォーマンスが落ちる
そうなんですね、この辺りはExUnit事情がわからないので判断しかねますが、
ExUnitのコード的にはfunction_og.php内で解決できそうなので、
↓の様な形で画像サイズを取得してタグへ追加してとりあえず事なきを得ましたので、シェアしておきますね。

https://gist.github.com/tomhat/6cfa2e0bc8c6d32c9425d3f101829a14

**Comment by kurudrive** [comment]
あー！そうですね...
wp_get_attachment_image_src で普通にサイズ取れるからできましたね...。
近日対応しておきます ＞＜

|・ｗ・）.oO（ プ...プルリク歓迎です... ）

**Comment by tomhat** [comment]
あ、こちらの勘違いでなくてよかったです＾＾
先程修正したコードのプルリクさせていただきました。

**Comment by kurudrive** [comment]
@tomhat ありがとうございました。
コード短く改変しましたが、おそらく意図した動作はすると思います。
次回リリース時に反映されます。

**Comment by tomhat** [comment]
対応ありがとうございます！
