### ISSUE TITLE
LTG コンテンツエリア投稿ウィジェットでは”stickyクラス”が付与されない

### ISSUE THREAD

**Issue by spyderman2** [vektor-inc/VK-All-in-One-Expansion-Unit#441]
お世話になっております。

LTG コンテンツエリア投稿ウィジェットでは、固定表示投稿の”stickyクラス”が付与されず、背景色が変化しません。

投稿ページの記事一覧では”stickyクラス”が付与され、他の記事と区別できます。

ウィジェットでは背景が白のままなので、通常の記事と区別することができません。

これはこのような仕様なのでしょうか？
よろしくおねがいします。
![SnapCrab_NoName_2019-11-26_0-19-15_No-00](https://user-images.githubusercontent.com/57128790/69552977-b44a1180-0fe2-11ea-98f0-19a2d01ec93d.jpg)
![SnapCrab_NoName_2019-11-26_0-18-42_No-00](https://user-images.githubusercontent.com/57128790/69552979-b44a1180-0fe2-11ea-8039-3fff46128e65.jpg)

**Comment by kurudrive** [comment]
WordPressコアの get_post_class関数の中身が以下になっており、
投稿トップページに指定したページでのみ stickey クラスを出力するようになっています。

```
	// sticky for Sticky Posts
	if ( is_sticky( $post->ID ) ) {
		if ( is_home() && ! is_paged() ) {
			$classes[] = 'sticky';
		} elseif ( is_admin() ) {
			$classes[] = 'status-sticky';
		}
	}
```

**Comment by kurudrive** [comment]
下記を子テーマのfunctions.phpなどに書けばいけると思います。

```
add_filter( 'post_class', 'dokodemo_sticky' );
function dokodemo_sticky( $classes ) {
	global $post;
	if ( is_sticky( $post->ID ) ) {
			$classes[] = 'sticky';
	}
	return $classes;
}
```
