### ISSUE TITLE
サイトおよび管理画面でNotice

### ISSUE THREAD

**Issue by pooh-kamakura** [vektor-inc/vk-all-in-one-expansion-unit#524]
PHPのバージョンを上げたところ、全てのページで上部にNoticeが表示されるようになりました。

Notice: Undefined index: common in 〜/wordpress/wp-content/plugins/vk-all-in-one-expansion-unit/initialize.php on line 82

複数のレンタルサーバーおよびローカル環境で確認。
WordPressのバージョンは5.4.2、他のプラグインは全て停止、テーマはどれを使っても変化なし。

【現象が起きたバージョン】
　PHP7.3.9, 7.4.2, 7.4.7

【今まで問題なかったバージョン】
　PHP7.3.1

**Comment by drill-lancer** [comment]
これ４日前に気になったので修正済みです。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/commit/ad0361f543eb8221e69ba6344d0df8ffe4c9c559

**Comment by pooh-kamakura** [comment]
最終更新: 6日前 だったので、次のバージョンですね。
アップデートを待ちます。
ありがとうございました。

**Comment by kurudrive** [comment]
先程 9.25.0.1 アップデートしました。

**Comment by pooh-kamakura** [comment]
ご連絡ありがとうございます。修正確認しました。
