### ISSUE TITLE
vk all in one expansion unit widgetにクラスをつける方法が知りたいです。

### ISSUE THREAD

**Issue by Lark0000** [vektor-inc/vk-all-in-one-expansion-unit#578]
今vk all in one expansion unit widgetのプラグインを使ってサイト制作中です。

JavaScriptで動きをつけたいのでクラスをつけたいと思っていたのですが、
そもそもクラスを指定できる空欄が見つかりません。

外観→ウィジェット→どこにクラス指定したらいいのか？。。。。

vk all in one expansion unit widgetを使ったことのある方や
知っている方がいらしましたら、回答をください

お願いします。

**Comment by kurudrive** [comment]
現状独自のクラス名を追加する機能はない状態ですが、
ウィジェットの種類に関するclass名は出力されていますし、個別のウィジェットに対してつけるのであればid名に対してjsの動きを指定するのではまずいですか？

ちなみにどのウィジェットにどんな動きをつける想定ですか？

**Comment by Lark0000** [comment]
迅速な回答ありがとうございます。

管理画面からクラス名を指定できればいいと思っていたのですが、なさそうですね。

VK PR BlocksやVKお問合せボタンなどです。
動きに関しましては下からふわっと表示させたいと思っています。

ありがとうございます。

**Comment by kurudrive** [comment]
結構必要な感じですか？
内容的に機能追加は可能なのですが、このプラグインも５年経過してはじめて挙がってきたリクエスト内容なので無いと絶対に困る！ぜひ追加して欲しい！という状況でなければそのままいきたいかなと...
と、言うのと、急ぎでなければ来年あたりからサイト全体をブロックエディタで構築する形式にWordPressがかわっていくので、PR Blocks や お問い合わせボタンブロックは既に存在しているので、そちらは任意のクラスを指定できるので、
半年後くらいにはその方式で出来るようになるかなと...。

**Comment by Lark0000** [comment]
あったら便利だと思います。

なければないで違った動きをつけたりしてみます。
回答ありがとうございました
