### ISSUE TITLE
「ページトップへ戻るボタン」の横に「PAGE TOP」と表示される

### ISSUE THREAD

**Issue by massa0503** [vektor-inc/vk-all-in-one-expansion-unit#582]
- プラグインバージョン： 9.34.0.0
- ブラウザ：Firefox 80.0.1(64bit)、Google Chrome 85.0.4183.102（Official Build） （64 ビット）
- OS：Windows 10 Home 64bit

本日、プラグインの更新をしたところ、「ページトップへ戻るボタン」の横に「PAGE TOP」と表示されるようになりました。
更新履歴等を拝見しますと、モバイル端末で本ボタンを非表示にするオプションが追加される過程で、
本ボタンのoverflowがvisibleに変わったためかと思われますが、こちらは不具合か仕様変更のどちらでしょうか。

**Comment by kurudrive** [comment]
対応済みのためcloseとさせていただきます。

また症状出ましたらご連絡くださいませ。
