### ISSUE TITLE
気の早い話ですが、PHP 8 による PHP非推奨：必須パラメーター debug.logの以下リスト。

### ISSUE THREAD

**Issue by ifNoob** [vektor-inc/vk-all-in-one-expansion-unit#632]
PHP Deprecated:  Required parameter $attributes follows optional parameter $classes in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/common-block.php on line 103
PHP Deprecated:  Required parameter $option_name follows optional parameter $tab_label in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/admin/admin-main-setting-page.php on line 148
PHP Deprecated:  Required parameter $sanitize_callback follows optional parameter $tab_label in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/admin/admin-main-setting-page.php on line 148
PHP Deprecated:  Required parameter $render_page follows optional parameter $tab_label in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/admin/admin-main-setting-page.php on line 148
PHP Deprecated:  Required parameter $raw_array follows optional parameter $array in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/noindex/noindex.php on line 258
PHP Deprecated:  Required parameter $raw_array follows optional parameter $array in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/noindex/noindex.php on line 280
PHP Deprecated:  Required parameter $options follows optional parameter $array in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/noindex/noindex.php on line 280
PHP Deprecated:  Required parameter $instance follows optional parameter $is_modified in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/other-widget/widget-new-posts.php on line 130
PHP Deprecated:  Required parameter $instance follows optional parameter $is_modified in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/other-widget/widget-new-posts.php on line 183
PHP Deprecated:  Required parameter $attributes follows optional parameter $classes in /Users/***/Local Beta Sites/***/app/public/wp-content/plugins/vk-all-in-one-expansion-unit/inc/vk-blocks/hidden-utils.php on line 30

**Comment by kurudrive** [comment]
@ifNoob ご報告ありがとうございます。

@drill-lancer @mthaichi 
急ぎじゃないですがPHP8環境でテスト・必要に応じて修正よろしくお願いいたします。

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/650

修正いたしました。
報告ありがとうございました。
