### ISSUE TITLE
バージョンアップ後、連絡先情報の電話番号の文字が赤くなる

### ISSUE THREAD

**Issue by pooh-kamakura** [vektor-inc/vk-all-in-one-expansion-unit#645]
テーマLightningでプラグインVK All in One Expansion Unitを使用しています。

ExUnit をバージョンアップしたところ、連絡先情報の電話番号の文字色が変わりました。

現在のバージョン 9.52.1.0
以前のバージョン 9.50.0.0

ブラウザの開発ツールで確認したところ、

.veu_contact .contact_txt_tel {
    padding: 5px 0;
    font-size: 28px;
    line-height: 105%;
    font-weight: 700;
    color: var(--vk-color-primary);
}

--vk-color-primaryが#c00のため赤くなっているようです。

この色を変更するにはどうすればいいのでしょうか？
以前のようにカスタマイズのLightning デザイン設定で決めたキーカラーを使うことはできないのでしょうか？

**Comment by kurudrive** [comment]
Lightning のバージョンはいくつですか？

**Comment by pooh-kamakura** [comment]
Lightning バージョン: 13.8.11 です。

**Comment by kurudrive** [comment]
@pooh-kamakura 
13.8.13 アップしましたので、更新通知が表示されましたらアップデートしてご確認ください。

**Comment by pooh-kamakura** [comment]
早速の対応ありがとうございます。
もう一つ以前から気になっていた点がありますので、別に書きます。
