### ISSUE TITLE
幅768pxの時、VK 3PR エリアの画像横に文字が回り込む

### ISSUE THREAD

**Issue by pooh-kamakura** [vektor-inc/vk-all-in-one-expansion-unit#647]
Lightning＋ExUnit使用
気付いたのは数ヶ月前ですが、現バージョンでも同じでした。

横幅767px以下の時は、画像が幅一杯になりますが、
ちょうど768pxの時は画像の横に隙間が出来て文字が回り込みます。

@media (min-width:576px) {
 .container {
  max-width:540px
 }
}
@media (min-width:768px) {
 .container {
  max-width:720px
 }
}

@media screen and (max-width:768px) {
 .veu_3prArea_image {
  width:138px;
  margin:0 1em 0 0;
  float:left
 }
}

**Comment by pooh-kamakura** [comment]
お世話になっております。
先ほどExUnitを9.60.0.0にバージョンアップしたところ、横幅ちょうど768pxの時の回り込みは解消されていましたが、575px以下のスマホ表示でも画像が大きくなってしまいました。これはこういう仕様に変更されたのでしょうか？

スマホの時は画像を小さくコンパクトにまとめた表示がありがたく、クライアントもこの部分を気に入っていたので、とても困っています。

**Comment by pooh-kamakura** [comment]
最初の説明が不足していて申し訳ありませんでした。

タブレットサイズの時は3PRエリアが横に３つ並ぶのでコンテナ部分の1/3しか幅がなく、138pxの画像横に文字を回り込ませる余裕はありません。
スマホサイズの時は3PRエリアが縦に並ぶので、画像横に文字が回り込んだ方が見やすいです。

@media (min-width:768px)
と
@media screen and (max-width:768px)
が混在していたため、ちょうど768pxの時に設定が矛盾します。
maxかminのどちらかに統一していただければ問題ないと思います。

**Comment by kurudrive** [comment]
@pooh-kamakura 

多分 9.60.1.0 で大丈夫だと思います。

※ 3PRウィジェットを使わなくても現在はブロックエディタを使えばカラムブロックなどで構築できるようになっていますので、ブロックエディタの利用も検討ください。
