### ISSUE TITLE
G3 右下表示のページトップへ戻るボタンのaタグにtext-decoration-styleがあたっています

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-all-in-one-expansion-unit#661]
ページトップへ戻るボタンの下部にグレーのダッシュ線が表示されます。
aタグの text-decoration-style が効いているようです。

(max-width: 991.98px)以下の画面幅だとダッシュ線は表示されず大丈夫です。
ご確認よろしくおねがいします！

**Comment by arborvitae666** [comment]
G3に変更したところ、同じ現象に遭遇して調べてみましたが、
vkExUnit_style.cssの `.page_top_btn:hover` には `text-decoration:none` があるのに、
 `.page_top_btn` には `text-decoration:none` がないのが原因のようです。
ご確認お願いいたします。

とりあえずの対処としましては、
`a.page_top_btn { text-decoration: none; }`
でなんとかなっています。

**Comment by kurudrive** [comment]
@ChiakiKouno @arborvitae666 
こちら修正済みなので close します。
もし最新版で同じ症状が出るようでしたら reopen するか新規issueでご連絡ください。
