### ISSUE TITLE
ExUnitの「お問い合わせ情報」の表示パターンを増やしたい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#664]
カバーブロックなどの中に入れやすいように、枠・背景色なし のパターンが欲しい。

- [ ] 仕様を考える
- [ ] 実装する

---

元のカード
https://trello.com/c/VQyfoqQx/2194-exunit%E3%81%AE%E3%80%8C%E3%81%8A%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B%E6%83%85%E5%A0%B1%E3%80%8D%E3%81%AE%E8%A1%A8%E7%A4%BA%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%82%92%E5%A2%97%E3%82%84%E3%81%97%E3%81%9F%E3%81%84

**Comment by kurudrive** [comment]
ブロックパターンで実装すれば良いのでClose
