### ISSUE TITLE
【確認待ち】CTA _ 未設定だとおそらく管理画面で「表示しない」のプルダウンでも実際には最初に登録されているCTAが適用される

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#666]

**Comment by kurudrive** [comment]
@drill-lancer 

対応ありがとうございます。

false を '0' に変更のような場合、プログラムがどういう結果を返すのかを目視確認では PHPの仕様変更によって挙動がかわる事もありえるので、PHPUnitテストを書いてください。

テストをするために必要に応じてメソッドの構成を書き換えてもかまいません。

**Comment by drill-lancer** [comment]
@kurudrive 
false を '0' に変更したというか、下記で選択肢の value が 0 になってます。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/b4c42e17c224d5cc384eebf50f665339dc2f9843/inc/call-to-action/package/class-vk-call-to-action.php#L635-L641

数字の 0 で保存しても 文字列 '0' に保存時に変換されるようなので今回はこれで通ったと思われます。

**Comment by kurudrive** [comment]
@drill-lancer 

ありがとうございます。

0 の 場合と '0' の場合でもプログラムの書き方によって挙動はかわりますし、
じゃあそれがどういう挙動をする仕様なのか、
「この条件の時には必ずこういう結果を返す」という想定に対する保証ができるものはやるべきなので、
忌避続きPHPUnitを書いてください。

PHPUnitは、もっと難しい複合条件のケースで目視テストを初期実装・何か修正の度に毎回やってられないとか、
テストの書いてないコードは相手にされなかったりするので、書けるものは書く癖をつけて書き慣れるように訓練していきましょう！

**Comment by drill-lancer** [comment]
@kurudrive
テストユニットの作成が完了したので PR を OPEN します。
