### ISSUE TITLE
SNSアイコンの対応関係ズレ

### ISSUE THREAD

**Issue by hayashier** [vektor-inc/vk-all-in-one-expansion-unit#672]
いつも利用させていただいています。ありがとうございます。

最近、SNSのアイコンと実際の中身の対応関係がずれるようになりました。

![sns_misalignment](https://user-images.githubusercontent.com/12432095/121188857-7949bf00-c8a4-11eb-9838-68f886ac9ef1.png)

過去の履歴を確認させていただきましたところ、以下のPRが関係しているようです。

- PR
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/660

**Comment by kurudrive** [comment]
@hayashier 
Oh... 大変失礼しました。
ご報告ありがとうございます！

**Comment by kurudrive** [comment]
@hayashier 

ご報告ありがとうございました！
9.61.6.0 にて修正リリースいたしました！

**Comment by hayashier** [comment]
迅速にご対応いただき、驚きました。ありがとうございます！
