### ISSUE TITLE
【確認待ち】【5.8対応】DeprecatedなどのWarningが出る

### ISSUE THREAD

**Issue by miminari** [vektor-inc/vk-all-in-one-expansion-unit#677]
5.8βにおいて、VK Blocks と同じく

`Deprecated:  block_categories の使用はバージョン 5.8.0 から非推奨になっています ! 代わりに block_categories_all を使ってください。 in /home/vs4/www/vk-block-test/wp-includes/functions.php on line 5381`

などのWarningが表示されるので対応しましょう。

related https://github.com/vektor-inc/vk-blocks-pro/issues/566

**Comment by drill-lancer** [comment]
@miminari 
すでに対応済みでしたがプルリクするのを忘れてました。

**Comment by miminari** [comment]
@drill-lancer さすがです！PRありがとうございます！
