### ISSUE TITLE
デフォルトサムネイル機能で指定された画像がcoreの「最新の投稿」ブロックだと編集画面で表示されない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#680]
記事に登録したアイキャッチ画像は表示されるが、
デフォルトサムネイルの画像だと編集画面では出ない。

対応できるものなのか要調査

**Comment by drill-lancer** [comment]
編集画面だと、記事リストを取得⇒各記事に画像があればその画像を取得して表示という流れを
 JS でしているので割り込む余地はなさそうです。
https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/latest-posts/edit.js

**Comment by drill-lancer** [comment]
対応できそうにないので一旦 Close
