### ISSUE TITLE
CTA機能のお知らせ

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#686]
CTAをフッター直上に前幅で配置できるようになりました

### 今までのCTA機能の問題点

  * 本文欄末尾に表示される → そこじゃなくて「フッター直上」に「全幅」で配置したい
  * フッター上部のウィジェットエリアに、CTAウィジェットを配置 → 非表示にしたいページがあっても非表示設定はウィジェットには効かない（仕様）。

という問題があり、フッター直上に全幅のCTAを配置する事が簡単ではありませんでした。

#### 個別ページでのCTAの非表示指定がウィジェットにも反映されるように（9.46.0.0）

フッター上部のウィジェットエリアにCTAウィジェットを配置し、
CTAを表示したくないページでは、記事編集画面で「表示しない」を選択すれば非表示になるように変更しました。

今まで、ウィジェットは強制的に表示したいケースなど想定して、記事側の「表示しない」を指定してあってもウィジェットには適用しない設定でしたが、現実問題そのようなケースの方が稀で、「表示しない」が適用された方が実用性が高いので変更しました。

#### Call To Action で CTAの出力場所のアクションフックを指定する事ができるように（9.45.0.0）

ExUnit設定 > メイン設定 > Call To Action で CTAの出力場所のアクションフックを指定する事ができるようになりました。

Lightningであればフッター上部にウィジェットで配置すれば同じように表示はできますがアクションフックからの表示の場合は以下のメリットがあります。

* 投稿タイプ毎に表示するCTAを指定可能
* 表示したい箇所にウィジェットエリアがなくてもアクションフックがあればそこに表示可能

※アクションフックとは
プログラム上に予め用意された場所で、ユーザーが指定したPHPの処理をする事ができるWordPressの機能。
例えば Lightning のテーマファイルの /_g3/index.php を見てみると do_action( ではじまる記述がたくさんあります。

**Comment by kaorock72** [comment]
@kurudrive お知らせ公開と、Slack、SNSでのシェア完了しました！
https://www.vektor-inc.co.jp/product-update/exunit-9-63-cta/

**Comment by kaorock72** [comment]
@kurudrive 記事内にフッター直上のCTA画像の追加と、アクションフックからの表示のメリットを目立たせるようにしてみました！

**Comment by kurudrive** [comment]
@kaorock72 ありがとうございました！
