### ISSUE TITLE
【確認待ち】カスタマイズ画面でSNS表示ボタンの制御が効かない疑惑確認・修正

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#706]
↓ この tweet関連
https://twitter.com/bissybissy/status/1432414472317009920

**Comment by kurudrive** [comment]
@drill-lancer これ挙動確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
確認します。

**Comment by drill-lancer** [comment]
@kurudrive 
カスタマイザーも設定画面も正常に動作しているようです。
キャッシュの疑いが濃厚かと

**Comment by drill-lancer** [comment]
最初に管理画面で設定しないとカスタマイザーの内容が反映されない模様
確認します。
