### ISSUE TITLE
[お知らせ待ち ][ SNSボタン ] クリップボードにコピーを追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#707]
https://vws.vektor-inc.co.jp/forums/topic/add-share-copy

twitter でシェアした時にデフォルトで入る内容と同じものがクリップボードにコピーされる感じで良いかなと。

- [ ] アイコンを手動で作る必要があるはず。たぶん。 @goutetsuguma さん よろしくお願いいたします。

**Comment by drill-lancer** [comment]
タイトルと URL をコピーすれば OK ですね

**Comment by kurudrive** [comment]
@drill-lancer 「シェア用のタイトル（設定によって記事タイトルやカスタムフィールドの値）」とURLで（・ｗ・

**Comment by kurudrive** [comment]
@drill-lancer 
ありがとうございます。

シェアボタンでしか使わないので /inc/sns/ ディレクトリ内で完結するように構成してください。
コピーボタンがアクティブな設定の時だけでOKです。
fontawesome のアイコンが使えるなら使っても問題ありません。

**Comment by kurudrive** [comment]
これ今からやります。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！

**Comment by kurudrive** [comment]
@kaorock72 
コピーボタン追加しましたん。

**Comment by kaorock72** [comment]
@kurudrive お知らせ公開とシェア完了しました！
https://www.vektor-inc.co.jp/product-update/exunit-9-66-0-0-copybutton-add/
