### ISSUE TITLE
【確認待ち】[ カスタム投稿タイプマネージャー ] 設定を保存したら自動的にパーマリンク更新されるように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#711]
新規でカスタム投稿タイプを作ったりした時に、パーマリンクを保存せずに「ページが見つかりません」になるという意見が後を絶たないため。

**Comment by drill-lancer** [comment]
参考になりそうなもの
https://torounit.com/blog/2015/09/02/2077/

**Comment by kurudrive** [comment]
カスタム投稿タイプマネージャーの投稿が保存されたタイミングで走らせる感じかなと想定（・ｗ・
