### ISSUE TITLE
[ シェアボタン ] 表示位置を CTA同様アクションフックに指定出来るように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#712]
ExUnit > メイン設定 > Call To Action 参考

- [ ] 翻訳
- [ ] お知らせ記事

**Comment by drill-lancer** [comment]
@kurudrive 
フィルターフックの場合記事前と記事後の設定がありますが、
アクションフックの場合は
- 1つの入力エリアでカンマ区切り pr 改行区切りで複数指定できるようにする
- 2つの入力エリアを用意してそれぞれで１つ指定できるようにする
あたりで考えています。

個人的にはカンマよりは改行区切りほうが良いように思えます。
あと、アクションフックがあるところは限定的ですが３つ以上の場所に配置したい人もいそうなので
１つの入力エリアで改行区切りが良さそうです。

**Comment by kurudrive** [comment]
@drill-lancer 改行区切りで良いと思いますー。

**Comment by drill-lancer** [comment]
マージされたので Close
