### ISSUE TITLE
[ お知らせ待ち ][ ページトップ ] iPhone などでスムーススクロールが効かない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#713]
https://vws.vektor-inc.co.jp/forums/topic/%E3%82%A2%E3%83%B3%E3%82%AB%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%AE%E3%82%B9%E3%83%A0%E3%83%BC%E3%82%B9%E3%82%B9%E3%82%AF%E3%83%AD%E3%83%BC%E3%83%AB%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

以下でも発生を確認
https://demo.dev3.biz/lightning-g3

**Comment by kurudrive** [comment]
@kaorock72 

更新情報のお知らせよろしくお願いいたします。

ExUnit > メイン設定 で スムーススクロール設定を追加

CSS を選ぶと、javascriptを読み込まずにCSSだけで処理するので読み込みが少し軽量になります。
ただし、Safariではスムーススクロールになりません。

**Comment by kaorock72** [comment]
@kurudrive お知らせ公開とシェア完了しました！
https://www.vektor-inc.co.jp/product-update/exunit-9-66-0-0-smooth-scrolling/
