### ISSUE TITLE
SNS ボタンの Twitter で「OGPなどの投稿タイトルの変更」にチェックを入れないと動作しない

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vk-all-in-one-expansion-unit#722]
「OGPなどの投稿タイトルの変更」にチェックを入れると動作します。

どうやらタイトルとサイト名を区切る際の縦棒`|`が悪さしているみたいです。
縦棒を全角`｜`にすると動作するようです。

縦棒`|`が urlencode されないのが原因のようなのでこちら側で urlencode してしまうのもありかも・・・

参考：
https://www.php.net/manual/ja/function.urlencode.php
https://www.seil.jp/doc/index.html#tool/url-encode.html

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございまするー！

**Comment by kurudrive** [comment]
対応済 close
ありがとうございました！
