### ISSUE TITLE
【確認待ち】シェアボタンの Hatena の API の値が返ってなくて console がエラーを吐いているので調査・修正

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#741]
今村君実装なので詳細は僕も知りません...。

**Comment by drill-lancer** [comment]
これのことなのかよくわかりません
https://b.hatena.ne.jp/guide/bbutton

**Comment by kurudrive** [comment]
ExUnit の Hatena ボタンが ブックマーク数をAPIかなんかで取得して表示してるとかそんなしくみになってるのではないかと思うけどそのあたりでのエラーじゃないかなと思うけど僕も詳しくはワカリマセン。

**Comment by drill-lancer** [comment]
これを見つけたけど使い方がピンと来ません。
http://developer.hatena.ne.jp/ja/documents/bookmark/apis/getcount

**Comment by mthaichi** [comment]
確認中・・・

**Comment by mthaichi** [comment]
@kurudrive 以下、調査結果と相談です。

# 原因
はてなのブックマーク数をはてなのAPI経由で取得して表示させているのですが、そこで問題が起きています。

- はてなのAPIはAjax経由でたたきにいけない。
- そこで、「はてなのAPIをたたくAPI」を仕込む仕組みが実装されています。それが  
``` /wp-json/vk_ex_unit/v1/hatena_entry/<対象URLをエンコードしたもの>  ```
です。
- 対象URLをエンコードしたものをパラメータに取るのですが、XSERVERでは Apacheの AllowEncodedSlashes というオプションが off になっているようで、この場合、URLの中に スラッシュ(/)をエンコードした%2Fが入っていると 404エラーになるようです。 https://lightning.vektor-inc.co.jp/wp-json/vk_ex_unit/v1/hatena_entry/https%3A%2F%2Flightning.vektor-inc.co.jp%2Fdemo-site%2F     は404エラーになります。
- 「はてなのAPIをたたくAPI」が404のためエラーになっています。

# さらなる問題
上記原因を探っている間に気づいたのですが、ExUnitのSNS設定の「投稿数」の「GET (Default)」と「POST」の挙動が逆です。以下の箇所で  (bool) ( 'post' !== $opt['entry_count'] );  は (bool) ( 'post' === $opt['entry_count'] );  の誤りです。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/2b3d240e18261a0e90b26cd2591be01984a83e75/inc/sns/function-sns-btns.php#L381

# そこで対応策
- XSERVER問題に対応するには、スラッシュをいったん他の文字列に変換して、はてなのAPIを叩く際にもとに戻すという処理で切り抜けられるのではないかと思います。
- Get と Post が逆の件ですが、私としては、正規の動作に直して、アナウンスするのが良いと思います。しれっとラベルを入れ替えるということもできなくないですが、企業がやることとしては不誠実かなと感じます。

ということで、上記ご確認の上で、この対応で良いかご検討ください。

**Comment by kurudrive** [comment]
あら、すみません、
完全に共有不足でした。
僕の知ってる範囲では、
Defaultの方はリクエストが少なく速度が早いが、エックスサーバーではエラーになる。
これはエックスサーバーの仕様上避けられない。
そのためPostにすると解消する。

という状態が正常で、
「Post にしたのにエラーが出るからおかしい」

というのが今回のissueの趣旨でした。

で、今確認したら、たしかに Post でエラーが出るけどGETにすると出ないから逆になっちゃってるという事なんですね...

という事は、僕が過去にデフォルトをPostに変更しようとして変更方法を間違えてた疑惑が浮上...
変更履歴確認します...。

**Comment by mthaichi** [comment]
@kurudrive そうですね。そうなると挙動が逆になっていることが主原因になりますね。POST設定なのにGETで取得しようとして、URLのクエリパラメータに不正な文字が入っているのでエラーになっています。
「エックスサーバーの仕様上避けられない。」ことも上記に書きましたように、おそらく・・・ですが、対処可能だと考えておりますので、そっちも対応したほうがいいなら対応させていただきますー。

**Comment by kurudrive** [comment]
@mthaichi 
こちら 設定逆になっちゃってる問題修正よろしくお願いいたします。
