### ISSUE TITLE
【VK_FB Page Plugin】ios15.1でFacebook pageが表示されない（「IPアドレスを非公開」をオフにすると表示される）

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#742]
macのsafari15.1で症状を確認できました。

▼報告のあった内容
https://trello.com/c/EdfYv1kO/4530-%E3%83%97%E3%83%A9%E3%82%A4%E3%83%99%E3%83%BC%E3%83%88%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%AE%E5%95%8F%E3%81%84%E5%90%88%E3%82%8F%E3%81%9B

https://developers.facebook.com/docs/plugins/page-plugin
でコードを生成してHTMLに貼り付けても、「IPアドレスを非公開」がONになっていると、うまく表示されないので、facebookの問題な気もしますが、facebook側の問題か、こちらのコードの問題かを調べるタスクになります。

**Comment by kurudrive** [comment]
facebookの問題につき close
