### ISSUE TITLE
［有効化設定の不具合］ウィジェット有効化設定のチェックがどこかに入っていないとExUnitのチェックが入らない&外せない

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#747]
プライベートサポートのお問い合わせでチェックができないとのご相談がありました。
確認したところ、ExUnitの「ウィジェット有効化設定」のどれかにチェックが入っていないと、VK All in One Expansion Unit 有効化設定のチェックができないようでした。（変更を保存を押しても元に戻ってしまう）
そしてExUnitのウィジェット有効化設定にチェックを入れると、もうチェックが外せないのと外そうとして「変更を保存」をすると、前回チェックを外したはずのVK All in One Expansion Unit 有効化設定が元に戻ってしまうようでした。

**Comment by drill-lancer** [comment]
@kurudrive 
これ僕が見てみます。
