### ISSUE TITLE
[ OG処理 ] カスタム投稿タイプアーカイブでOGの処理が該当の投稿を反映させてしまう

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#749]
https://vws.vektor-inc.co.jp/forums/topic/custom-post-type-og-title

- [x] 年明け対応
- [x] PHPUnitを書いてください

**Comment by drill-lancer** [comment]
@kurudrive 
OG タイトルの仕様について質問です。
組み合わせは下記でよろしいでしょうか？

検索結果（キーワードあり）：Search Results for : %s
検索結果（キーワードなし）：Search Results
is_front_page() ：現状のまま
! is_front_page() && is_home()：投稿アーカイブ用の固定ページの名前
is_singular()：現状のまま
その他アーカイブページ：[get_the_archive_title()](https://developer.wordpress.org/reference/functions/get_the_archive_title/)

**Comment by kurudrive** [comment]
@drill-lancer はい、OKです！よろしくお願いいたします。

**Comment by drill-lancer** [comment]
マージされたので Close
