### ISSUE TITLE
有効化のON/OFFが初期状態に戻ってしまうときがある

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-all-in-one-expansion-unit#754]
ダッシュボードの[VK All in One Expansion Unit 有効化設定]のページで思ったようにオプションを選べません

- チェックを外しても初期設定にすぐ戻ってしまいます
- 大雑把にいうと、いちばん上にある[有効化]をチェックするとすべてが有効、チェックをはずすとすべて無効…のように画面上は見えながら、[変更を保存]をクリックすると初期状態に戻ってしまいます
- [ウィジェット]のチェックが入っているとうまく設定できるような気がします、[ウィジェット]を外して[変更を保存]をクリックすると初期状態に戻ってしまう

ローカル、本番(さくら、ヘテムル)とも発生します
WordPressは5.8.3、5.9 RC3で試してます
個人的で恐縮です〜

---
2022.1.28 石川追記
以下フォーラムでの報告
https://vws.vektor-inc.co.jp/forums/topic/exunit-active-setting-9-70

**Comment by kurudrive** [comment]
こちらわりと最近 @drill-lancer さんが修正してませんでしたっけ？
気のせいかな？

**Comment by kurudrive** [comment]
@drill-lancer 月曜で良いのでこれ確認よろしくお願いいたします。

**Comment by goutetsuguma** [comment]
@kurudrive @drill-lancer 

> こちらわりと最近 @drill-lancer さんが修正してませんでしたっけ？

おそらくこのissueだったと思います。

https://github.com/vektor-inc/vk-all-in-one-expansion-unit/issues/747

**Comment by drill-lancer** [comment]
@kurudrive 
多分無効化できない機能がいくつかあるのでそのことを指していそうです。

**Comment by sysbird** [comment]
@drill-lancer  @kurudrive
夜分すみません、先程developにマージしてしまったんですが気になる点がありまして、
明日は不在ですので書いておきます 

- ウィジェット有効化にしていったん保存しないと、ウィジェットのオプションが表示されません、合ってますでしょうか？
- VK Blocksの項目がありますが、選択できないで合ってますでしょうか？

**Comment by kurudrive** [comment]
> VK Blocksの項目がありますが、選択できないで合ってますでしょうか？

これは正常です。
