### ISSUE TITLE
【翻訳確認待ち】ウィジェット一覧に「固定ページ本文」ウィジェットがない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#763]
ので追加よろしくお願いいたします。

**Comment by drill-lancer** [comment]
![Page Content Widget](https://user-images.githubusercontent.com/38716787/152707315-a8d85eeb-26d7-462f-a204-89df65fe1a34.jpg)

@kurudrive 
存在自体はしていますが翻訳があたっていないから気づいていないだけのようです。

https://translate.wordpress.org/projects/wp-plugins/vk-all-in-one-expansion-unit/stable/ja/default/?filters%5Btranslated%5D=yes&filters%5Bstatus%5D=waiting

**Comment by kurudrive** [comment]
@drill-lancer あー、なるほど、ありがとうございます！
