### ISSUE TITLE
【9.73.2.0 以降確認】シェアボタン: Facebookの公式カラーの更新

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-all-in-one-expansion-unit#781]
最新のデジタル用のFacebookブルー
RGB - 24 119 242
HEX - 1877F2
https://www.facebook.com/brand/resources/facebookapp/logo

現在のシェアボタンに設定されているカラー：
background: #425dab;
box-shadow: 0 2px 0 #344e84;

**Comment by kurudrive** [comment]
修正しました。
9.73.2.0 以降で反映になりますー。

**Comment by kurudrive** [comment]
※ 確認完了したら Project を完了に変更よろしくお願いいたします。

**Comment by ChiakiKouno** [comment]
確認しました！ありがとうございました！
