### ISSUE TITLE
【機能追加要望】カテゴリごとにアイキャッチ画像を設定できる機能があったらいいなと思ったので書いておきます。

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#783]
私自身もあったらいいなと思ったのですが、ちゃんと更新されているプラグインが見つからなかったのでExUnitの機能であったらいいなと思いましたがむずかしいでしょうか。
むずかしいようでしたらCloseしてください。

https://vws.vektor-inc.co.jp/forums/topic/%e3%82%ab%e3%83%86%e3%82%b4%e3%83%aa%e3%81%94%e3%81%a8%e3%81%ab%e3%82%a2%e3%82%a4%e3%82%ad%e3%83%a3%e3%83%83%e3%83%81%e7%94%bb%e5%83%8f%e3%82%92%e8%a8%ad%e5%ae%9a%e3%81%99%e3%82%8b%e6%96%b9%e6%b3%95#post-62591

**Comment by kurudrive** [comment]
需要と実装コストのバランスが合わないため
