### ISSUE TITLE
【確認待ち】ExUnit のアイコンが 画像ファイルで処理していないので、画像タグ読み込みでエラーを吐く

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#793]
普通に SVG か png 形式のファイル参照じゃまずい？

![スクリーンショット 2022-03-12 1 19 05](https://user-images.githubusercontent.com/3272660/157906554-c2a66a62-ae77-44f0-9c0b-7805f826ba81.png)

![スクリーンショット 2022-03-12 1 20 57](https://user-images.githubusercontent.com/3272660/157906669-edbdcab9-6455-44e2-a6c9-fa3c58758acb.png)

**Comment by goutetsuguma** [comment]
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/803

こちら修正しました。お手隙の時にご確認お願いしますmm
