### ISSUE TITLE
更新エラー

### ISSUE THREAD

**Issue by sama55** [vektor-inc/vk-all-in-one-expansion-unit#797]
V8系より古いPHP環境でVK All in One Expansion Unitプラグインを9.73.2.0に上げると致命的なエラーが発生して管理画面にアクセスできなくなります。すぐに対応した方がいいかもしれません。

原因箇所：wp-content/plugins/vk-all-in-one-expansion-unit/admin/admin.php L48
対処方法：L48を修正してFTPでアップロード
対処前）
$custom_page = add_menu_page(
$page_title,
$menu_title,
$capability_required,
$menu_slug,
$callback_function,
$icon_url,　　←※不要なカンマ
);
対処後）
$custom_page = add_menu_page(
$page_title,
$menu_title,
$capability_required,
$menu_slug,
$callback_function,
$icon_url
);`

**Comment by kurudrive** [comment]
@sama55 ご報告ありがとうございます。
9.73.3.0 にて修正いたしました！

**Comment by kurudrive** [comment]
@sama55 

> V8系より古いPHP環境で

発生したPHPのバージョンは具体的にいくつでしょうか？

**Comment by sama55** [comment]
XSERVERの7.4.25です。

**Comment by kurudrive** [comment]
@sama55 ありがとうございます！
ですよね、7.4はテストサーバーでも自動テストも通っているので考え込んでました（汗）

**Comment by sama55** [comment]
もっと正確に情報を出すべきでした。私も慌てて・・・
再現で苦労させてすみませんでした。

**Comment by kurudrive** [comment]
いえいえ、何にせよ早い報告は被害を少なくできるのでとても助かりました。
今後ともなにかありましたらよろしくお願いいたします！
