### ISSUE TITLE
Google Analyticsのタグはログイン時は出力しないでほしい

### ISSUE THREAD

**Issue by sysbird** [vektor-inc/vk-all-in-one-expansion-unit#800]
ダッシュボードにログインしている場合にもGoogle Analytics のタグを出力するかどうか？選べると嬉しい
編集プレビュー中にもPVカウントされて、見てるの自分だけでは？と心配になるので…選べるといいなぁ

**Comment by kurudrive** [comment]
これはたぶん、Analytics 側で自分をカウントしない設定があったはず（・ｗ・

※ 10年くらい前の知識なので今は不明

**Comment by sysbird** [comment]
Analytics 側ではIPアドレスで除外できたような(2-3年前の知識)
ベクトル公式サイトのようにリモートで複数人で運営している場合は、面倒だしあまり気にしてないでしょうかね

すみません、個人的には他のそうやってるプラグインから移行したのでほしいなーと

**Comment by ChiakiKouno** [comment]
ログインしてるしてないは関係なくなってしまうのですが、
Chromeからのアクセスだけ除外でよろしければ、私はChrome拡張機能でGoogle謹製のアドオンを入れてます。
これ入れておくととりあえず自分のChromeからのアクセスは全部無視されてるはず。。
https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh?hl=ja

**Comment by sysbird** [comment]
ですね、ありがとうございます！
運営が自分だけでしたらアドオンで足りるのですけど、お客さんはちょっとむずかしいかなー

あったら嬉しいなぐらいですので、失礼しました

**Comment by kurudrive** [comment]
|・ｗ・）.oO（ 多分実装難しくないからプルリクいただいてもええんやで... ）

**Comment by sysbird** [comment]
おぉ、自分で追加してもいいんですね！
ちょっと挑戦〜

**Comment by kurudrive** [comment]
@sysbird ありがとうございましたー。
