### ISSUE TITLE
PHP 7.2 と 5.6 の PHPUnit テストって復活できない？

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#802]
wp-env の都合とかで使えなくなったんですっけ？

---

→ 7.2 のテスト無しというのはまずいので再検討する必要がある

https://capitalp.jp/2021/10/14/wordpres-phpunit-updated/
https://github.com/tarosky/rich-taxonomy/blob/main/composer.json

**Comment by drill-lancer** [comment]
PHP Unit のポリフィルの都合なので・・・

**Comment by kurudrive** [comment]
@drill-lancer ファイナルアンサー？

**Comment by drill-lancer** [comment]
@kurudrive 
FA
