### ISSUE TITLE
【機能追加要望】「VK カテゴリー/カスタム分類リストブロック」と「VK アーカイブリストブロック」がほしい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#820]
ウィジェットではあるけど、ブロックでは無いのでissueをたてました

https://vws.vektor-inc.co.jp/forums/topic/vk-%E3%82%AB%E3%83%86%E3%82%B4%E3%83%AA%E3%83%BC-%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E5%88%86%E9%A1%9E%E3%83%AA%E3%82%B9%E3%83%88%E3%82%92%E5%9B%BA%E5%AE%9A%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%A7

- [ ] VK カテゴリー/カスタム分類リストブロック
- [ ] VK アーカイブリストブロック

**Comment by kurudrive** [comment]
VK Blocks の方で実装するのでこちらは close

https://github.com/vektor-inc/vk-blocks-pro/issues/1249
https://github.com/vektor-inc/vk-blocks-pro/issues/1290
