### ISSUE TITLE
外観>カスタマイズ>ExUnit設定>お問い合わせ情報>お問い合わせ先URLから日本語のURLの設定

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#833]
試してみたら、文字列に変換されると更新できないのかな、、？とおもいました。
[https://demo.dev3.biz/lightning-g3-pro/お問合せ](https://demo.dev3.biz/lightning-g3-pro/%E3%81%8A%E5%95%8F%E5%90%88%E3%81%9B)　→ 更新できる
https://demo.dev3.biz/lightning-g3-pro/%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b/ →更新できない

---

https://vws.vektor-inc.co.jp/forums/topic/%e5%a4%96%e8%a6%b3%e3%82%ab%e3%82%b9%e3%82%bf%e3%83%9e%e3%82%a4%e3%82%baexunit%e8%a8%ad%e5%ae%9a%e3%81%8a%e5%95%8f%e3%81%84%e5%90%88%e3%82%8f%e3%81%9b%e6%83%85%e5%a0%b1%e3%81%8a

**Comment by drill-lancer** [comment]
マージされたので Close
