### ISSUE TITLE
「headタグ内のtitleタグのテキスト」の機能に注意書きが必要

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#834]
「※トップページの場合は ExUnit→メイン設定→トップページの<title>タグ に入力します。」
のような注意書きが必要

https://vws.vektor-inc.co.jp/forums/topic/head-%e3%82%bf%e3%82%b0%e5%86%85%e3%81%ae-title-%e3%82%bf%e3%82%b0%e3%81%ae%e3%83%86%e3%82%ad%e3%82%b9%e3%83%88-%e3%81%8c%e5%8f%8d%e6%98%a0%e3%81%95%e3%82%8c%e3%81%aa%e3%81%84

**Comment by kurudrive** [comment]
@goutetsuguma 対応しました！
