### ISSUE TITLE
【確認待ち】有効化設定の初期設定がブロックテーマの場合ブロックテーマ用の設定になるように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#835]
有効化設定の初期値で、ブロックテーマの場合以下のものは無効になるように（ブロックテーマじゃなくても無効のもあるかも）

* ウィジェット
* 投稿ループ前ウィジェットエリア
* お問い合わせセクション
* Call To Action
* アイキャッチ画像自動挿入
* 広告の挿入
* ナビメニューclassの改変（FSEで効いてるのか要確認（多分効かないと思うけど））

**Comment by drill-lancer** [comment]
マージされたので Close
