### ISSUE TITLE
Articleの構造化データを出力する機能を新規追加する

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#836]
https://www.suzukikenichi.com/blog/google-added-new-author-markup-best-practices-to-the-article-structured-data-documentation/

* まずは 投稿（post）にだけ表示すればOK
* 複数ユーザーの共著には対応しない

#### type

構造化のユーザー情報には author @type 属性がある。
これはWordPressのユーザーメタ情報に type 属性を追加して、プルダウンで個人か組織かを選択させる。

#### sameAs

通常のURLは標準のプロフィール情報のURLを割り当てれば良いが sameAs は該当するものがないので @type 同様 ユーザーメタ情報を追加します。

---

@doshimaf さんが作業する場合は ExUnit についてファイル構造概要は @drill-lancer さんに説明を受けてください。

---

## 後日実装

- [ ] Articleの構造化データを表示する投稿タイプをチェックボックスで指定出来る機能を追加
- [ ] 投稿毎に構造化データを出力しないチェックボックス追加

**Comment by kurudrive** [comment]
@doshimaf 実装ありがとうございます。すみません、重大な勘違いしてました。
今回追加していたのは Article の構造化データで、Article の構造化データの中の author 指定のガイドラインが Google から案内された形なので、機能名としては「著者情報の構造化データ」ではなく「記事の構造化データ」になります。
なので、機能名や関数名で Author Structure みたいになっている部分を軒並み Article Structure みたいな感じで Article に変更よろしくお願いいたします... (´；ω；｀)

**Comment by doshimaf** [comment]
リリースされたのでcloseします。
