### ISSUE TITLE
CTA ブロック新規作成

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#843]
現在ウィジェットで存在するのでそのダイナミックブロック版

※ VK Blocks Pro のレビューがあればそのレビュー優先でよろしくお願いいたします。

**Comment by kurudrive** [comment]
@goutetsuguma アイコンよろしくお願いいたしますー！

**Comment by goutetsuguma** [comment]
@kurudrive CC @drill-lancer 
ボタンにマウスカーソルが乗っているイメージでつくってみましたが、ちょっとわかりずらいですかね、、？
これは勉強会までに入れておきたいやつですよね、、？！
もし急ぎでしたら後ほど微調整したいと思っております

![icon](https://user-images.githubusercontent.com/5525368/186601430-0c152cf3-ab64-4114-8868-0a2c76d779ec.svg)

**Comment by drill-lancer** [comment]
@goutetsuguma 
今回は下記を書き換える感じです。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/f010d1644deadf4b399ffec6abf8a0c30eabd41a/inc/call-to-action/package/blocks/block.jsx#L10-L14

**Comment by goutetsuguma** [comment]
@drill-lancer 
@kurudrive 

ありがとうございます！iconのところを変えてプッシュしておきました！
ご確認お願いいたします
