### ISSUE TITLE
CTAとお問い合わせ 有効化設定を無効化するとブロックでエラーになる

### ISSUE THREAD

**Issue by shimotmk** [vektor-inc/vk-all-in-one-expansion-unit#856]
CTAとお問い合わせ 有効化設定を無効化すると
「このブロックでエラーが発生したためプレビューできません。」
になります

CTAとお問い合わせブロックは事前にデータを保存していることが前提なので、有効化設定を無効化した際はCTAブロックとお問い合わせブロックは無効化(インサーターから非表示)で良いでしょうか？

**Comment by shimotmk** [comment]
@kurudrive 
確かに無効化した際に「このブロックでエラーが発生したためプレビューできません。」は出た方が良い(これはコアの機能)

エラーが発生するブロックを配置できるようになっているのは不親切かなと思った次第でした

**Comment by shimotmk** [comment]
いや、でもブロックとして用意していることを示せるのはインサーターしかないから別に今のままで良さそうですね
一旦現状で問題ないと思うのでcloseします

**Comment by kurudrive** [comment]
@shimotmk ありがとうございます。

なるほど、CTAが登録されてない状態でブロックが配置できてしまうという事ですね。
あれ？今確認したところCTA登録がなくて配置しても「選択してください」が表示されるだけで「このブロックでエラーが発生したためプレビューできません。」にならなくないですかね？

**Comment by shimotmk** [comment]
@kurudrive 
有効化設定を無効化した時です。

CTA登録の有無は関係なしです

**Comment by kurudrive** [comment]
@shimotmk 

あれ？確かに有効化してないのにブロック選択が出来てしまいますね。
いや、これ、有効化してないプラグインのブロックが選択できる（選択はできるがエラーになる）のと同じような状態なので出ちゃまずいような気がします（汗

**Comment by kurudrive** [comment]
正常 : CTA有効化状態 -> 無効化した : ブロックがエラーになる
異常 : CTA無効化状態 : ブロックが配置できてしまう（ブロックはエラーになるだけ）

**Comment by shimotmk** [comment]
@kurudrive 
ありがとうございます
調整します

**Comment by kurudrive** [comment]
@shimotmk よろしくお願いいたします (￣人￣)

**Comment by shimotmk** [comment]
いつのまにか治っていたのでclose
