### ISSUE TITLE
[ 構造化データ（記事） ] vektor-inc.co.jp でユーザーを保存しても更新されない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#865]
他のサイトだと普通に保存されますが vektor-inc.co.jp だと 構造化データの情報だけアップデートされないようなので、調査よろしくお願いいたします。
basic認証などが影響してるのかも。
調査のため一時的に解除などしてもかまいません。

**Comment by doshimaf** [comment]
@kurudrive 昨日から調査しはじめました。
昨日では、たしかに構造化データの情報を変更して保存しても、アップデートされなかったのですが、
先程再度試したところ保存できました。
原因などは不明ですが、取り急ぎ報告です。

**Comment by doshimaf** [comment]
@kurudrive
本日再確認したところ、保存して正常に更新されました。
また、公開画面のheadにも正常に出力されていました。
