### ISSUE TITLE
【お知らせ待ち】UAとGA4のタグを両方出力できるようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#866]
## 現状の問題点

どちらか一つのタグしか出力できない

---

### 改修内容

現状、IDの入力欄が2つで、ラジオボタンで切り替える方式だが、この方式だと両方のタグは出力できない。
GA4用と旧ユニバーサルアナリティクス用でそれぞれ入力を分けた上で、タグを出力させる。

---

GA4タグの確認
データストリーム > （対象サイトを選択）> タグの実装手順を確認する > 手動でインストールする

GA4タグサンプル
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-************"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-8MFSZKBCJ8');
</script>
```

## 新しい設定項目

このサイトで使用する Google アナリティクスの ID を入力して下さい。

#### GA4
[  ]
例）G-XXXXXXXXXX

#### ユニバーサル アナリティクス
[  ]
例）UA-

◎ ユニバーサル アナリティクスのコード ( analytics.js )
◎  ノーマルのコード ( analytics.js )

- [ ]  ログインしているユーザーの追跡を無効化

---

## 注意事項

今まで設定された値による意図する動作が、
今回の改修後も正常に動作するように互換処理・テストをしっかり書くこと。
仕様確認のためにもテストを先に書いて、テスト内容を確認した方が良い

```
/**
 * どの GoogleAnalyticsタグを出力するか？
 * 
 * @return string : GA4 / GA4_and_UA / GA4_and_normal / UA / normal
 */
function veu_get_analytics_type(){

}
```

**Comment by drill-lancer** [comment]
@kurudrive 

```
◎ ユニバーサル アナリティクスのコード ( analytics.js )
◎ ノーマルのコード ( analytics.js )
```

これって今でも必要ですか？
今タグを取得しにいったら

UA-XXXXXXXX-XX の場合

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX-XX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXX-XX');
</script>
```

G-XXXXXXXXXX の場合

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-XXXXXXXXXX');
</script>
```

でどちらも gtag.js に統一されていますが・・・

むしろ analitics.js から gtag.js に移行が始まっているという話もあります。

https://support.google.com/analytics/answer/10271001#zippy=%2C%E3%81%93%E3%81%AE%E8%A8%98%E4%BA%8B%E3%81%AE%E5%86%85%E5%AE%B9

**Comment by kurudrive** [comment]
@kaorock72 
と、いう事で GA4のタグと両方出せるようになりましたので次回お知らせ記事よろしくお願いいたします。

* もともと GA4 のタグは出せた。
* UAと両方出そうとすると タグマネージャー 使わないといけなかった。
* ExUnit 単体で両方計測できるようになった。
* まだ GA4 のタグ設定してない方は是非

**Comment by kaorock72** [comment]
@kurudrive 最新のExUnit9.83.0.0でもまだ翻訳があたらないみたい？です。Lightning Pro版デモサイトやローカルなど、いくつかの環境で確認し、プラグインの矯正翻訳アップデートも使ってみました。記事は作成して非公開で準備しておきます。翻訳されたらキャプチャ取って、明日か連休明け？かどこかのタイミングで公開とシェアしようかと思いますーー、せっかくなら連休前にお知らせしたいところですが。

**Comment by kaorock72** [comment]
キャプチャを追加して公開完了しましたので、クローズいたします！
https://www.vektor-inc.co.jp/product-update/exunit-9-82-0-ua-ga4-tag/
