### ISSUE TITLE
［機能追加要望］Follow me boxに別のSNS（インスタ）も追加したい

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#892]
インスタを追加したいというご要望がありましたので、issueにあげておきます。

（CTAでの対応をご案内したところ、そちらでやってみますとのことでしたので、実装するにしても優先度は低めかもしれません）

**Comment by goutetsuguma** [comment]
CTAで対応で解決しましたのでCloseしますmm 石川さんありがとうございました！

**Comment by kurudrive** [comment]
_|＼○_ﾋｬｯ ε=＼＿○ﾉ ﾎｰｳ!!
