### ISSUE TITLE
【確認待ち】 [ X-T9 ] ページ編集下部のExUnit の Custom CSS が反映されません

### ISSUE THREAD

**Issue by ChiakiKouno** [vektor-inc/vk-all-in-one-expansion-unit#900]
WP v6.1.1
X-T9 v1.3.4
ExUnit 9.85.0.1

lingning.nagoya に既存の特設ページをX-T9で作成中のページに移植していて気がつきました。
ページ編集下部のExUnit の Custom CSS に何を入力しても反映されません。

<img width="944" alt="Screenshot 2023-01-13 at 5 15 50 PM" src="https://user-images.githubusercontent.com/43702482/212284714-2e1c85ad-545d-4e64-96f1-27fafb6405b2.png">

カスタムCSSに入力したり、コアのカスタムHTMLブロックに記載すると問題なく反映されました。

**Comment by drill-lancer** [comment]
@kurudrive 
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/blob/6015b11107dadad3081427a09c035009ddeaaf07/inc/css-customize/css-customize-single.php#L13-L34

X-T9 の場合上記の `have_posts()` が false を返すためかループが実行されず何も表示されないということになっているようです。

**Comment by drill-lancer** [comment]
マージされたので Close
