### ISSUE TITLE
「メタディスクリプションタグを出力」にチェクを入れて、抜粋欄を空にした場合は「設定」→「一般設定」のキャッチフレーズが表示されるはずが空になってしまう

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#903]
ExUnitの有効化設定→「メタディスクリプションタグを出力」にチェクを入れて、抜粋欄を空にした場合、「設定」→「一般設定」のキャッチフレーズが表示されるようですが、空になってしまうようでした。
おそらく空の場合はキャッチフレーズが表示される仕様が正しいと思われます。

何か私の勘違いもあるかもしれませんので、その時は教えてくださいmm

**Comment by drill-lancer** [comment]
@goutetsuguma @kurudrive 
抜粋欄に全角空白のみが入ってる場合表示されません。（空白のみが表示される）
