### ISSUE TITLE
タイトルタグ設定機能をカスタム投稿やwoocommerceの商品の投稿ページでも使用できるようにしたいとのご要望

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#915]
現状この機能は固定ページや投稿では使用できるけど、カスタム投稿やwoocommerceの商品の投稿ページでも使用したいという要望がありましたので、issueにしました。可能でしょうか、、？

https://vws.vektor-inc.co.jp/forums/topic/seo%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6-2#post-73239

**Comment by kurudrive** [comment]
対応済みclose
