### ISSUE TITLE
【翻訳待ち】ブロックの翻訳があたらなくなっているので直したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#926]
@drill-lancer 
こちらも書籍の都合があるので優先確認よろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer うーむ、翻訳したけどなかなか反映されぬ...うーむ...

**Comment by drill-lancer** [comment]
@kurudrive 
副作用狙いですが一応プルリクしてみました。
https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/930

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
