### ISSUE TITLE
【相談】headタグ内のtitleタグのテキスト機能はアーカイブページでは使用できない仕様（？）だと思われますので、注意書きを書いておくのはいかがでしょうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#932]
https://vws.vektor-inc.co.jp/forums/topic/seo%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6-2
【質問】
headタグ内のtitleタグのテキスト機能はアーカイブページでは使用できない仕様であっておりますか？
もしそうなら、以下のページや機能のところに注意書きを追記したいです。

・【済】ExUnitの説明ページに注意書きを追加　←注意書き追加しました。
https://ex-unit.nagoya/ja/about/wp_title
・headタグ内のtitleタグのテキスト機能のところに注意書きを追加

---

いったんAssigneesには仕様に詳しそうな石川さんとリックさんを入れさせていただきました。
質問の段階ですので、すぐに着手でなくて大丈夫です🙇‍♂️

**Comment by kurudrive** [comment]
@goutetsuguma 
はい、個別指定はできないです。
ただ、多分WordPress標準だと
カテゴリー名 > サイト名
のところが
カテゴリー名 | サイト名
になるみたいな微妙な変更はあります。

**Comment by drill-lancer** [comment]
いしかわさんはんだんで Close
