### ISSUE TITLE
【確認待ち】［質問：メタディスクリプション］メタディスクリプションタグを出力にチェックを入れて抜粋が空の場合は、CTAが入っているとCTAの部分が読み込まれるのでしょうか

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#941]
投稿・固定ページでCTA（本文欄使用）が表示されている場合、CTAの本文欄部分がdiscriptionに表示されていました。
サンプルの[このページ](https://demo.dev3.biz/lightning-g3-pro/service/)のdiscriptionをみると以下になっているのですが、
抜粋が空でCTAの本文欄が入っている場合、CTAの本文欄が反映される仕様であっていますか？

`<meta name="description" content=".vkb-outer-d766b6c4-7642-47d5-9f98-a6fe1d35fe93{background-image: url(https://www.vektor-inc.co.jp/vk-blocks-tmpl-images/programming-942487_1920.jpg); }ご予約はこちらこの部分には、自社について説明が入ります。自社のコンセプトや理念など、大切にしていることについて説明しましょう。お客様に一番伝えたいことを" /><script type="text/javascript">`

できれば、CTAの本文欄部分ではなく、ページの本文の先頭から240文字文が反映されると良いなと思いましたがいかがでしょうか。

**Comment by kurudrive** [comment]
あら？本文が入る前の動作しちゃってるのかな？きっと @drill-lancer さんが調査してくれると思います！
ありがとう！！

**Comment by kurudrive** [comment]
@goutetsuguma リリースしました！

**Comment by goutetsuguma** [comment]
ありがとうございます！Closeします
