### ISSUE TITLE
[ CTA ] コンソールでエラーが出てる

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-all-in-one-expansion-unit#949]
wp.data.select( 'core' ).getEntityRecords( 'postType', 'cta', { per_page: -1, include: [12100] })

CTAの登録がない時に出てるのかな...

**Comment by drill-lancer** [comment]
@kurudrive 
私の環境ではどうにも発生しないのですが・・・

**Comment by drill-lancer** [comment]
問題なさそうだったので Close
