### ISSUE TITLE
【確認待ち】「Twitter」の名前やアイコンを「X」に変更

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vk-all-in-one-expansion-unit#993]
https://discord.com/channels/1010092469863587892/1010092470471774210/1137051344658772071

> Font Awesome にも「X」のロゴが出たということは何かしらやらないと行けない気がするのでどなたか🙏  ExUnit のソーシャルブックマークボタンのあたり？
> https://fontawesome.com/icons/x-twitter?f=brands&s=solid
> https://fontawesome.com/icons/square-x-twitter?f=brands&s=solid

---

#### ソーシャルメディア連携
・有効化設定画面の「ソーシャルメディア連携」設定部分のTwitterの名前部分
・SNS Settings のTwitterの名前と表示アイコン

#### ウィジェット
・VK プロフィールウィジェットのTwitter の名前と表示アイコン

もれがあるかもしれません

---

Assigneesには一旦、開発者メンバーを入れさせていただきましたので、作業される方はご自身のアイコンだけに変更してもらえると、他の方と作業が被らないかなと思います。

**Comment by drill-lancer** [comment]
行きまーす
