### ISSUE TITLE
VK_最近の投稿　非公開記事まで表示される

### ISSUE THREAD

**Issue by FarbiEorz** [vektor-inc/vk-all-in-one-expansion-unit#999]
VK_最近の投稿 ウィジェットで非公開記事まで表示されてしまいます。

公開記事のみ表示にするかどうかのオプションなどあればよいかと思います。

とりあえず現状widget-new-post.phpの$query_argsに'post_status' => 'publish'を追加して使っています。

**Comment by kurudrive** [comment]
@FarbiEorz 
編集権限のないユーザーかログアウトした状態でも表示されますか？

**Comment by kurudrive** [comment]
現状で一般のユーザー（該当記事を編集する権限がないユーザー）には非公開記事は表示されない仕様になっていると思います。
編集権限があるユーザーにも非表示にすると、編集するために管理画面に戻る手間が発生するためです。
これは WordPress 標準の投稿リストなどでも同様の仕様ですのでクローズさせていただきます。

もし ログアウトした状態でも非公開記事が表示されるという事であればあらためて reopen してください。
※ サーバーキャッシュなどで編集権限を持ったユーザーでアクセスした状態をサーバーがキャッシュを保存して、そのキャッシュを別のユーザーが見るという事はありますので、その場合はサーバーキャッシュなど確認ください。
VK_最近の投稿 ウィジェットだけ変更しても WordPress標準の各投稿リスト表示箇所は同じ症状になると思いますので。
